import {NextResponse} from 'next/server';
import {prisma} from '@/lib/prisma';
import {currentUser} from '@/lib/auth';
import {createEvidenceStoragePath,uploadEvidenceFile,validateEvidenceFile} from '@/lib/supabase-storage';
import {createNotificationSafely} from '@/lib/notifications';

const SIGNATURE_MARKER='__POC_SIGNATURE__';

export async function POST(r:Request){
 const u=await currentUser();if(!u||u.role!=='TRANSPORTER')return NextResponse.json({error:'Transporter access required'},{status:403});
 const form=await r.formData();const bookingId=String(form.get('bookingId')||'');const releasedBy=String(form.get('releasedBy')||'').trim();const condition=String(form.get('condition')||'').trim();const damageNotes=String(form.get('damageNotes')||'').trim();const confirmed=String(form.get('confirmed')||'')==='true';const signature=form.get('signature');const photos=form.getAll('photos').filter((x):x is File=>x instanceof File&&x.size>0);
 if(!bookingId)return NextResponse.json({error:'Booking is required'},{status:400});if(releasedBy.length<2||releasedBy.length>120)return NextResponse.json({error:'Enter the name of the person releasing the vehicle'},{status:400});if(!['NO_DAMAGE','EXISTING_DAMAGE'].includes(condition))return NextResponse.json({error:'Confirm the vehicle condition at collection'},{status:400});if(condition==='EXISTING_DAMAGE'&&!damageNotes)return NextResponse.json({error:'Add notes describing the existing damage'},{status:400});if(damageNotes.length>1500)return NextResponse.json({error:'Damage notes must be 1500 characters or fewer'},{status:400});if(!confirmed)return NextResponse.json({error:'Confirm the vehicle has been collected'},{status:400});if(!(signature instanceof File)||signature.size<=0)return NextResponse.json({error:'Release signature is required'},{status:400});if(photos.length<1)return NextResponse.json({error:'Add at least one collection photo'},{status:400});if(photos.length>8)return NextResponse.json({error:'You can upload up to 8 collection photos'},{status:400});
 const booking=await prisma.booking.findFirst({where:{id:bookingId,transporterId:u.id},include:{payment:true,job:true}});if(!booking)return NextResponse.json({error:'Booking not found'},{status:404});if(!['CONFIRMED','COLLECTION_SCHEDULED'].includes(booking.status))return NextResponse.json({error:'Collection evidence can only be submitted before the vehicle enters transit'},{status:400});if(!booking.payment||booking.payment.status!=='PAID')return NextResponse.json({error:'Customer payment must be secured before collection'},{status:400});
 const sv=await validateEvidenceFile(signature);if(!sv.ok)return NextResponse.json({error:`Signature: ${sv.error}`},{status:400});const valid=[] as {file:File,extension:string}[];for(const photo of photos){const v=await validateEvidenceFile(photo);if(!v.ok)return NextResponse.json({error:`Collection photo: ${v.error}`},{status:400});valid.push({file:photo,extension:v.extension});}
 try{const paths=[] as string[];for(const item of valid){const path=createEvidenceStoragePath(booking.id,u.id,item.extension);await uploadEvidenceFile(path,item.file);paths.push(path)}const signaturePath=createEvidenceStoragePath(booking.id,u.id,sv.extension);await uploadEvidenceFile(signaturePath,signature);const submittedAt=new Date();await prisma.$transaction(async(tx:any)=>{for(const path of paths)await tx.evidence.create({data:{bookingId:booking.id,uploaderId:u.id,type:'COLLECTION',imageUrl:path,note:'Proof of collection photo'}});await tx.evidence.create({data:{bookingId:booking.id,uploaderId:u.id,type:'COLLECTION',imageUrl:signaturePath,note:SIGNATURE_MARKER}});await tx.$executeRaw`UPDATE "Booking" SET "pocReleasedByName"=${releasedBy}, "pocCondition"=${condition}, "pocDamageNotes"=${damageNotes||null}, "pocSubmittedAt"=${submittedAt}, "status"='IN_TRANSIT'::"BookingStatus" WHERE "id"=${booking.id}`;await tx.trackingEvent.create({data:{bookingId:booking.id,status:'IN_TRANSIT',note:condition==='EXISTING_DAMAGE'?`Vehicle collected. Existing damage recorded: ${damageNotes}`:'Vehicle collected. No existing damage reported.',actorId:u.id}})});await createNotificationSafely({userId:booking.customerId,type:'DELIVERY',title:'Vehicle collected',body:'Your transporter has completed the collection condition report and your vehicle is now in transit.',href:'/customer'});return NextResponse.json({ok:true,submittedAt})}catch(e){console.error('Proof of collection submission failed',e);return NextResponse.json({error:'Unable to submit proof of collection right now'},{status:500})}
}
