import Link from 'next/link';
import Icon from './AboutPageIcon';

const questions=[
 ['Who is DriveDrop for?','DriveDrop is for customers who need vehicles moved and independent transporters looking for suitable vehicle transport work across the UK. Customers can request and compare quotes; transporters can submit quotes and manage their bookings.'],
 ['Does DriveDrop transport the vehicle?','No. DriveDrop is the marketplace connecting customers with independent transporters. Your chosen transporter carries out the vehicle movement. Agree collection, delivery and any access or loading requirements directly with them.'],
 ['What vehicles can I request transport for?','You can request transport for cars, motorcycles, vans, classic / prestige vehicles, motorhomes / campers, caravans / trailers, plant / farm and other vehicles. Include the vehicle’s condition and any special requirements so transporters can assess suitability.'],
 ['Where can I find help with a booking?','Open the booking in your account to review its details, message the other party and use the available report-a-problem controls. The Help page also provides guidance on bookings, payments and account questions.'],
];
export default function AboutDesktop(){return <div className="approvedPublicContent approvedPublic-about aboutDesktop">
 <section className="approvedPublicHero aboutPageHero"><div className="approvedPageWidth"><span className="approvedEyebrow">ABOUT DRIVEDROP</span><h1>Vehicle delivery. Made simpler.</h1><p>Connecting people who need vehicles moved with independent transporters across the UK.</p><div className="aboutActions"><Link className="btn orange" href="/get-quotes">Get transport quotes</Link><Link className="btn light" href="/how-it-works">How it works</Link></div></div></section>
 <section className="aboutBenefits"><div className="approvedPageWidth">{[['uk','Built for UK journeys','A marketplace designed for vehicle transport across the UK.'],['users','Connecting customers and transporters','Bringing together people who need vehicles moved with independent transporters.'],['records','Keeping the details together','Requests, messages and handover information in one place.']].map(([icon,title,copy])=><article key={title}><Icon name={icon}/><div><h2>{title}</h2><p>{copy}</p></div></article>)}</div></section>
 <section className="approvedPageWidth aboutIntro"><div><h2>A clearer way to move vehicles.</h2><p>Arranging vehicle transport means bringing together the right route, timing and transporter. DriveDrop gives customers a place to request quotes and compare their options.</p><p>For independent transporters, it provides a place to find suitable work, submit quotes and manage bookings from collection to delivery.</p></div><article><Icon name="car"/><h3>For customers</h3><p>Buying, selling or relocating? Share your vehicle and journey details, compare quotes and choose the transporter that suits your needs.</p><Link href="/for-customers">Explore customer services <Icon name="arrow"/></Link></article><article><Icon name="truck"/><h3>For transporters</h3><p>Review transport requests, quote for suitable jobs and keep your bookings, customer messages and handover records organised.</p><Link href="/for-transporters">Explore transporter services <Icon name="arrow"/></Link></article></section>
 <section className="aboutFeatures"><div className="approvedPageWidth"><h2>What DriveDrop brings together.</h2><div>{[['file','Clear requests','Route, vehicle, date and transport requirements.'],['search','Informed choices','Quotes, transporter profiles and customer feedback.'],['chat','Direct communication','Keep arrangements in your booking conversation.'],['circleCheck','Recorded handovers','Collection and delivery reports in one place.']].map(([icon,title,copy])=><article key={title}><Icon name={icon}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>
 <section className="approvedPageWidth aboutRole"><img src="/orange-design-preview/assets/about-handover.webp" alt="Customer and transporter reviewing a tablet beside a silver estate and recovery truck" width={2048} height={683}/><div><h2>A marketplace with a clear role.</h2><p>DriveDrop connects customers with independent transporters and provides tools to manage bookings.</p><p>Transporters carry out the vehicle movement. Customers and transporters agree the collection, delivery and any access or loading requirements for each job.</p><Link className="btn light" href="/how-it-works">See how it works</Link></div></section>
 <section className="approvedPageWidth aboutFaq"><div><h2>More about DriveDrop</h2><p>Answers to some common questions about how DriveDrop works.</p></div><div className="aboutFaqGrid">{questions.map(([question,answer])=><details key={question}><summary>{question}<span className="aboutFaqChevron"><Icon name="chevron"/></span></summary><p>{answer}</p></details>)}</div></section>
 <section className="aboutFinalCta"><div className="approvedPageWidth"><h2>Let’s get your next journey moving.</h2><div className="aboutActions"><Link className="btn orange" href="/get-quotes">Get transport quotes</Link><Link className="btn light" href="/register?account=transporter">Join as a transporter</Link></div></div></section>
 </div>}
