'use client';
import Link from 'next/link';
import {useState} from 'react';
import Icon from './ApprovedIcon';
const steps=[['file','Get Instant Quotes','Enter your collection and delivery details and receive quotes from verified transporters near you.'],['user','Compare & Choose','Review ratings, prices and reviews. Choose the transporter that best suits your needs.'],['calendar','Your Vehicle is Collected','Your chosen transporter collects your vehicle at the agreed time.'],['pin','Safe Delivery','Your vehicle is delivered safely to your chosen location. It’s that simple.']];
// Sample design content. Replace with verified marketplace data before production.
const reviews=[{quote:'Fantastic service from start to finish. Got quotes within minutes and my car was delivered the next day. Highly recommend DriveDrop!',name:'Sarah M.',place:'Bristol',image:'/orange-design-preview/assets/bmw-saloon.webp'},{quote:'Seeing verification and reviews before booking makes a huge difference.',name:'Daniel Brooks',place:'Audi A6',image:'/drivedrop-customer-daniel.webp'},{quote:'Much easier than ringing around transport companies.',name:'Priya Shah',place:'Land Rover Sport',image:'/drivedrop-customer-priya.webp'}];
const groups=[{title:'Quick Links',links:[['/how-it-works','How It Works'],['/for-customers','For Customers'],['/for-transporters','For Transporters'],['/about','About Us']]},{title:'Support',links:[['/contact','Contact Us'],['/help','FAQ'],['/terms','Terms & Conditions'],['/privacy','Privacy Policy']]},{title:'Your account',links:[['/login?account=customer','Customer Login'],['/login?account=transporter','Transporter Login'],['/register?account=transporter','Join DriveDrop']]}];
export default function ApprovedHomeSections(){const [reviewIndex,setReviewIndex]=useState(0);const review=reviews[reviewIndex];return <div className="approvedHomeSections approvedReferenceHome">
<div className="approvedPageWidth referenceStats" aria-label="Sample marketplace statistics for design preview"><div><strong>4.8/5 <span className="referenceStars" aria-label="Five stars">★★★★★</span></strong><small>from 2,000+ customers</small></div><div><strong>10,000+</strong><small>vehicles delivered</small></div><div><strong>Nationwide</strong><small>Trusted. Reliable. Professional.</small></div></div>
<div className="approvedPageWidth referenceMain"><section className="approvedHow referenceHow"><span className="approvedEyebrow">HOW DRIVEDROP WORKS</span><h2>A simpler way to move vehicles</h2><p>From quote to delivery, we make vehicle transport simple, secure and stress-free.</p><div className="referenceSteps">{steps.map(([icon,title,copy],index)=><article key={title}><b className="referenceStepNumber">{index+1}</b><span className="referenceStepIcon">{icon==='calendar'?<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><path d="M4 5h16v16H4z M4 10h16 M8 2v6 M16 2v6 M8 14h3v3H8z"/></svg>:icon==='pin'?<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 1a8 8 0 0 0-8 8c0 6 8 14 8 14s8-8 8-14a8 8 0 0 0-8-8m0 11a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/></svg>:<Icon name={icon}/>}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="referenceReviews" aria-label="Sample customer reviews"><div className="referenceReviewHeading"><div><span className="approvedEyebrow">TRUSTED BY THOUSANDS</span><h2>What our customers say</h2></div><div className="referenceReviewControls"><button type="button" aria-label="Previous review" onClick={()=>setReviewIndex(i=>(i+reviews.length-1)%reviews.length)}>‹</button><button type="button" aria-label="Next review" onClick={()=>setReviewIndex(i=>(i+1)%reviews.length)}>›</button></div></div><article className="referenceReviewCard" aria-live="polite"><div><span className="referenceQuote" aria-hidden="true">“</span><p>{review.quote}</p><span className="referenceStars" aria-label="Five stars">★★★★★</span><strong>{review.name}</strong><small>{review.place}</small></div><figure><img src={review.image} alt="Vehicle delivery preview" width={150} height={120}/><figcaption>Delivered with care</figcaption></figure></article></section></div>
<p className="referenceSampleNote">Design preview · Ratings, delivery totals and reviews are sample content.</p>
<footer className="referenceFooter"><div className="approvedPageWidth referenceFooterGrid"><Link href="/" className="referenceFooterLogo" aria-label="DriveDrop home"><img src="/orange-design-preview/assets/logo-white.svg" width={205} height={55} alt="DriveDrop — Vehicle delivery, simplified"/></Link>{groups.map(group=><nav key={group.title} aria-label={group.title}><h2>{group.title}</h2>{group.links.map(([href,label])=><Link key={href} href={href}>{label}</Link>)}</nav>)}<div className="referenceNewsletter"><h2>Stay in the loop</h2><p>Get the latest updates and transport tips.</p><div><input type="email" aria-label="Email address — newsletter coming soon" placeholder="Enter your email address" disabled/><button type="button" disabled title="Newsletter signup coming soon">Subscribe</button></div><small>Newsletter signup coming soon</small></div><div className="referenceSocial"><div aria-label="Social accounts coming soon">{[['Facebook','f'],['Instagram','◎'],['LinkedIn','in'],['YouTube','▶']].map(([label,symbol])=><span key={label} role="img" aria-label={`${label} — coming soon`} title={`${label} — coming soon`}>{symbol}</span>)}</div><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms of Service</Link></div></div><div className="approvedPageWidth referenceFooterBottom"><span>© {new Date().getFullYear()} DriveDrop. All rights reserved.</span><span>VEHICLES MOVE A BRIGHTER TOMORROW <i/></span></div></footer></div>}
