'use client';
import HowItWorksDesktop from './HowItWorksDesktop';
import {useState} from 'react';
import Link from 'next/link';
import Icon from './ApprovedIcon';
type Page='how-it-works'|'for-customers'|'for-transporters'|'about'|'help'|'contact';
const content:Record<Page,string[]>={
'how-it-works':['HOW DRIVEDROP WORKS','Simple. Transparent. Reliable.','From your first quote to the final delivery, keep the journey organised.'],
'for-customers':['FOR CUSTOMERS','Move Your Vehicle with Confidence','Request quotes, compare transporters and manage the details from one account.'],
'for-transporters':['FOR TRANSPORTERS','More journeys. More opportunities.','Find vehicle transport jobs and manage your work with DriveDrop.'],
about:['ABOUT DRIVEDROP','Vehicle delivery, simplified.','Connecting vehicle owners and independent transporters across the UK.'],
help:['HELP & SUPPORT','How can we help?','Find answers, get guidance and keep your journey moving.'],
contact:['CONTACT US','How can we help?','Find answers, get guidance and keep your journey moving.']};
export default function ApprovedPublicContent({page,questions}:{page:Page;questions:readonly (readonly [string,string])[]}){const [query,setQuery]=useState('');const [topic,setTopic]=useState('');const [eyebrow,title,description]=content[page];const transporter=page==='for-transporters';const help=page==='help'||page==='contact';const desktopQuestions=[...questions,['Where can I find payment and refund information?','Open Your deliveries to see the payment details for your booking. Any issued refund is shown on the booking. Use the booking’s report-a-problem controls if you need help with a delivery.']];const filtered=desktopQuestions.filter(([q,a])=>(q+' '+a).toLowerCase().includes(query.toLowerCase()));if(page==='how-it-works')return <HowItWorksDesktop/>;return <div className={`approvedPublicContent approvedPublic-${page}`}><section className={`approvedPublicHero${transporter?' isTransporter':''}${help?' isHelp':''}`}><div className="approvedPageWidth"><span className="approvedEyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p>{help?<form className="approvedHelpSearch" onSubmit={e=>{e.preventDefault();document.getElementById('approved-faq')?.scrollIntoView({behavior:'smooth',block:'start'})}}><input aria-label="Search help" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search for help articles, bookings, payments, delivery…"/><button className="btn orange" type="submit">Search <Icon name="search"/></button></form>:<Link className="btn orange" href={transporter?'/register?account=transporter':'/get-quotes'}>{transporter?'Join Our Transporter Network':'Get a Quote'} <Icon name="arrow"/></Link>}</div></section>
{help?<div className="approvedPageWidth approvedHelpBody"><h2>Browse by topic</h2><div className="approvedHelpTopics">{[['file','Bookings & Deliveries','Find your booking and follow your delivery.','delivery'],['pound','Payments & Refunds','Understand booking payments and proceeds.','payment'],['shield','Account & Verification','Manage your account and verification.','verification']].map(([icon,label,copy,key])=><button key={key} type="button" onClick={()=>{setTopic(label);setQuery(key)}}><Icon name={icon}/><h3>{label}</h3><p>{copy}</p><span>View help <Icon name="arrow"/></span></button>)}</div><section id="approved-faq"><div className="approvedSectionTitle"><h2>{topic||'Frequently asked questions'}</h2>{(topic||query)&&<button className="btn light" onClick={()=>{setQuery('');setTopic('')}}>Show all</button>}</div>{filtered.length?filtered.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>):<p>No matching answers. Try another search or open your account for booking support.</p>}</section><div className="approvedSupportBottom"><h2>Still need help?</h2><p>Open your account to find the delivery and its contact or problem-reporting controls.</p><div><Link className="btn orange" href="/login?account=customer">Customer login <Icon name="arrow"/></Link><Link className="btn light" href="/login?account=transporter">Transporter login</Link></div></div></div>:<><section className="approvedPageWidth approvedMarketing"><h2>{transporter?'Your business. All in one place.':'A clearer journey, from start to finish.'}</h2><div className="approvedFeatureGrid">{[['file','Request and compare','Enter the journey and vehicle details. Compare quotes, profiles and proposed collection dates.'],['chat','Keep in touch','Discuss arrangements in the booking conversation and keep the details together.'],['shield','Manage the journey','Review collection and delivery reports and confirm receipt from your account.']].map(([icon,title,copy])=><article key={title}><Icon name={icon}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="approvedPageWidth approvedMarketingSplit"><img src={`/orange-design-preview/assets/${transporter?'transporter-driver':'customer-portrait'}.webp`} alt={transporter?'Transporter and vehicle carrier':'Customer beside her vehicle'}/><div><span className="approvedEyebrow">BUILT AROUND YOUR JOURNEY</span><h2>{transporter?<>Stay focused on<br/>the road ahead.</>:<>Every detail.<br/>In one place.</>}</h2><p>Quotes, booking information, conversations and delivery updates are connected in your DriveDrop account.</p><Link className="btn orange" href={transporter?'/transporter':'/customer'}>Explore your account <Icon name="arrow"/></Link></div></section></>}
</div>}

