import Link from 'next/link';
import Icon from './ApprovedIcon';

const steps=[
 ['file','Tell us what needs moving','Add collection and delivery addresses, vehicle details, running condition, date and transport type. Create an account or log in to send your request.'],
 ['chat','Compare your quotes','Compare prices, transporter profiles, reviews and proposed dates. Ask questions before choosing a transporter.'],
 ['calendar','Book your transport','Accept a quote and complete the booking payment. Contact your transporter to agree collection time and handover arrangements.'],
 ['truck','Collection and updates','Your transporter records collection details and vehicle condition. Follow status updates and keep in touch through your booking.'],
 ['shield','Confirm delivery','Inspect your vehicle, review the delivery report and confirm receipt. Report any problem through your booking.'],
];
const questions=[
 ['Do I need an account?','Yes. Create a customer account or log in when submitting your request so you can manage quotes, messages and bookings.'],
 ['Can I move a non-running vehicle?','Yes. Select non-running in the vehicle details and explain any faults or loading requirements. Confirm that your chosen transporter has suitable equipment before booking.'],
 ['Which transport type should I choose?','Choose Driven if you want the vehicle driven, Open transport for an open carrier, or Enclosed transport for a covered carrier. Choose Any if you have no preference. Enclosed transport is available for cars, motorcycles and classic / prestige vehicles. Discuss suitability with the transporter before booking.'],
 ['What if there is a problem?','Open the booking in your customer account and use its report-a-problem controls. Include a clear description and any relevant evidence. Review the delivery details before confirming receipt.'],
];
export default function HowItWorksDesktop(){return <div className="approvedPublicContent approvedPublic-how-it-works howDesktop">
 <section className="approvedPublicHero howHero"><div className="approvedPageWidth"><span className="approvedEyebrow">HOW DRIVEDROP WORKS</span><h1>Your vehicle’s journey, step by step.</h1><p>Request quotes, choose your transporter and manage your delivery in one place.</p><div className="howHeroActions"><Link className="btn orange" href="/get-quotes">Get transport quotes <Icon name="arrow"/></Link><a className="btn light" href="#how-steps">See the steps <span aria-hidden="true">↓</span></a></div></div></section>
 <section className="howBenefits"><div className="approvedPageWidth">{[['globe','UK-wide transport','From local collections to long-distance delivery.'],['user','Compare independent transporters','Compare quotes and choose the right transporter for you.'],['shield','Manage everything in your account','Messages, updates and reports in one place.']].map(([icon,title,copy])=><article key={title}><Icon name={icon}/><div><h2>{title}</h2><p>{copy}</p></div></article>)}</div></section>
 <section id="how-steps" className="approvedPageWidth howProcess"><h2>From quote to delivery in five steps.</h2><div className="howStepGrid">{steps.map(([icon,title,copy],i)=><article key={title}><div className="howStepTop"><span>{i+1}</span><Icon name={icon}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section className="approvedPageWidth howPreparation"><img src="/orange-design-preview/assets/how-it-works-handover-wide.webp" alt="Driver and customer reviewing the vehicle condition on a tablet" width={1719} height={915}/><div className="howChecklist"><h2>Ready for collection?</h2><p>A few simple checks can help make collection smooth and keep your vehicle’s journey on track.</p><ul>{['Confirm collection and delivery contact details','Tell the transporter about access restrictions','Have keys ready and remove personal belongings','Mention faults, modifications or non-running condition','Agree who will be present at both ends'].map(line=><li key={line}><Icon name="check"/>{line}</li>)}</ul></div><div className="howFaq"><h2>Frequently asked questions</h2>{questions.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">⌄</span></summary><p>{answer}</p></details>)}</div></section>
 <section className="howAccountStrip"><div className="approvedPageWidth"><div><h2>Keep every detail in one place.</h2><p>Manage your journey through your customer account.</p></div>{[['chat','Messages','Agree arrangements with your transporter.'],['truck','Delivery updates','Follow collection and delivery status.'],['file','Handover reports','Review collection and delivery records.']].map(([icon,title,copy])=><article key={title}><Icon name={icon}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
 <section className="howFinalCta"><div className="approvedPageWidth"><h2>Ready to move your vehicle?</h2><p>Start with your collection, delivery and vehicle details.</p><div><Link href="/get-quotes" className="btn orange">Get transport quotes <Icon name="arrow"/></Link><small>Already booked? <Link href="/login?account=customer">Log in</Link></small></div></div></section>
 </div>}
