import Link from 'next/link';
import Icon from './TransporterPageIcon';

const steps=[
 ['user','Set up your profile','Add your business details and submit your driving licence and insurance documents for review.'],
 ['file','Find and quote for jobs','Review the route, date, vehicle condition and transport type. Quote for work you can fulfil.'],
 ['truck','Arrange and collect','Once booked, agree collection with the customer and complete the collection report.'],
 ['circleCheck','Deliver and record','Complete the delivery report. The customer reviews the handover and confirms receipt.'],
];
const questions=[
 ['What do I need to join?','Create a transporter account, add your business details and submit your driving licence and insurance documents for review. Keep your insurance valid and your profile information up to date.'],
 ['How do I quote for a job?','Open Available jobs in your transporter account. Review the route, vehicle, date, running condition and transport type, then submit your price and proposed collection date for a suitable job. Confirm any access or loading requirements before committing.'],
 ['What happens after my quote is accepted?','Once the booking payment is complete, contact the customer to arrange collection. Complete the collection report at handover, keep the customer updated and complete the delivery report when the vehicle arrives.'],
 ['Where can I check my proceeds?','Open Booked proceeds in your transporter account to see booking amounts and payment status, including work awaiting customer confirmation, amounts ready for release and paid amounts. Check each booking for details of any holds, fines or refunds.'],
];
export default function TransportersDesktop(){return <div className="approvedPublicContent approvedPublic-for-transporters transporterDesktop">
 <section className="approvedPublicHero transporterPageHero"><div className="approvedPageWidth"><span className="approvedEyebrow">FOR TRANSPORTERS</span><h1>Your next vehicle<br/>transport job starts here.</h1><p>Find UK vehicle delivery requests, quote for suitable work and manage your bookings in one place.</p><div className="transporterActions"><Link className="btn orange" href="/register?account=transporter">Join as a transporter <Icon name="chevron"/></Link><Link className="btn light" href="/login?account=transporter">Transporter login <Icon name="chevron"/></Link></div></div></section>
 <section className="transporterBenefits"><div className="approvedPageWidth">{[['route','Find suitable jobs','Review routes, vehicles and transport requirements.'],['quote','Quote on your terms','Set your price and proposed collection date.'],['laptop','Keep work organised','Messages, reports and proceeds in one account.']].map(([icon,title,copy])=><article key={title}><Icon name={icon}/><div><h2>{title}</h2><p>{copy}</p></div></article>)}</div></section>
 <section className="approvedPageWidth transporterProcess"><h2>From finding work to completing delivery.</h2><div className="transporterStepGrid">{steps.map(([icon,title,copy],i)=><article key={title}><span className="transporterNumber">{i+1}</span><Icon name={icon}/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
 <section className="approvedPageWidth transporterDetails"><img src="/orange-design-preview/assets/transporter-depot-phone.webp" alt="Transporter checking his phone beside a navy recovery truck at a vehicle depot" width={1774} height={887}/><div className="transporterChecklist"><h2>Be ready for the job.</h2><ul>{['Keep insurance and profile details up to date','Check loading and access requirements','Confirm the collection time with the customer','Record vehicle condition at each handover'].map(copy=><li key={copy}><span><Icon name="check"/></span>{copy}</li>)}</ul></div><div className="transporterAccount"><h2>Your work, in one place.</h2><ul>{[['file','Available jobs and your quotes'],['chat','Active deliveries and messages'],['file','Collection and delivery reports'],['pound','Booked proceeds and payment status']].map(([icon,copy])=><li key={copy}><Icon name={icon}/>{copy}</li>)}</ul></div></section>
 <section className="transporterProceeds"><div className="approvedPageWidth"><div><h2>Know where your proceeds stand.</h2><p>See booked proceeds, jobs awaiting customer confirmation and amounts ready for release or paid.</p></div><div className="transporterStatus"><div>{[['file','Booked proceeds','booked'],['clock','Awaiting confirmation','waiting'],['coins','Ready for release','ready'],['check','Paid','paid']].map(([icon,label,tone])=><div key={label} className={tone}><span><Icon name={icon}/></span><strong>{label}</strong></div>)}</div><p>Check your account for the status and details of each booking.</p></div></div></section>
 <section className="approvedPageWidth transporterFaq"><div><h2>Questions transporters ask</h2><p>Here are some of the most common questions about using DriveDrop as a transporter.</p></div><div className="transporterFaqGrid">{questions.map(([question,answer])=><details key={question}><summary>{question}<span className="transporterFaqChevron"><Icon name="chevron"/></span></summary><p>{answer}</p></details>)}</div></section>
 <section className="transporterFinalCta"><div className="approvedPageWidth"><h2>Ready to find your next job?</h2><div className="transporterActions"><Link className="btn orange" href="/register?account=transporter">Join as a transporter <Icon name="chevron"/></Link><Link className="btn light" href="/login?account=transporter">Transporter login <Icon name="chevron"/></Link></div></div></section>
 </div>}
