'use client';
import {useState} from 'react';
import Link from 'next/link';
import {type CustomerPayment,filterPayments,paymentTotals,paymentMonth,paymentDate,paymentMoney,paymentLabel,paymentStatuses,bookingPaymentHref} from '@/lib/customer-payments';
import styles from './payments.module.css';

function Icon({name}:{name:'download'|'card'|'refund'|'receipt'|'pin'|'shield'}){
 const paths={download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',card:'M3 4h18v16H3ZM3 9h18M6 15h4',refund:'m8 3-6 6 6 6M2 9h12a7 7 0 0 1 0 14',receipt:'M5 2h14v20l-3-2-4 2-4-2-3 2ZM8 7h8M8 11h8M8 15h5',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6Zm-5 10 3 3 6-6'};
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}
function Status({value}:{value:string}){return <span className={`${styles.status} ${value==='PAID'?styles.paid:value.includes('REFUND')?styles.refunded:styles.pending}`}>{paymentLabel(value)}</span>}
const receiptHref=(row:CustomerPayment)=>`/api/customer/payments/download?bookingId=${encodeURIComponent(row.bookingId)}&format=pdf`;
export default function PaymentsView({payments}:{payments:CustomerPayment[]}){
 const [q,setQ]=useState(''),[month,setMonth]=useState(''),[status,setStatus]=useState(''),[selectedId,setSelectedId]=useState(payments[0]?.id||'');
 const rows=filterPayments(payments,{q,month,status});
 const selected=rows.find(r=>r.id===selectedId)||rows[0];
 const totals=paymentTotals(rows);
 const months=Array.from(new Set(payments.flatMap(p=>p.paidAt?[paymentMonth(p.paidAt)]:[]))).sort().reverse();
 const download=(format:string)=>'/api/customer/payments/download?'+new URLSearchParams({format,q,month,status}).toString();
 return <main className={styles.page}>
  <header className={styles.heading}><div><h1>Payments</h1><p>View your payments, refunds and booking receipts.</p></div><a className={styles.button} href={download('pdf')}><Icon name="download"/>Download statement</a></header>
  {payments.some(p=>p.test)&&<p className={styles.testNotice}>Test payments are labelled below. Their receipts are test records.</p>}
  <section className={styles.summary} aria-label="Payment totals for current filters">{([['Total paid',totals.paid,'card'],['Refunded',totals.refunded,'refund'],['Net paid',totals.net,'receipt']] as const).map(([title,value,icon])=><article key={title}><Icon name={icon}/><div><span>{title}</span><strong>{paymentMoney(value)}</strong></div></article>)}</section>
  <div className={styles.columns}><section className={styles.history}><div className={styles.sectionHeading}><h2>Payment history</h2><span aria-live="polite">{rows.length} payment{rows.length===1?'':'s'}</span></div>
   <div className={styles.filters}><input aria-label="Search booking or vehicle" placeholder="Search booking or vehicle" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Payment month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">All dates</option>{months.map(m=><option key={m} value={m}>{new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z'))}</option>)}</select><select aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{paymentStatuses.map(s=><option key={s} value={s}>{paymentLabel(s)}</option>)}</select></div>
   {rows.length?<><div className={styles.tableScroll}><table><thead><tr><th>Booking / vehicle</th><th>Payment date</th><th>Amount paid</th><th>Status</th><th><span className={styles.srOnly}>Receipt</span></th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className={selected?.id===row.id?styles.selected:''}><td><button className={styles.selectRow} onClick={()=>setSelectedId(row.id)} aria-pressed={selected?.id===row.id} aria-label={`View payment breakdown for ${row.reference}, ${row.vehicle}`}><strong>{row.reference}</strong><span>{row.vehicle}</span></button>{row.test&&<small className={styles.testBadge}>Test payment</small>}</td><td>{paymentDate(row.paidAt)}</td><td>{paymentMoney(row.paidPence,row.currency)}</td><td><Status value={row.status}/></td><td>{row.paidPence>0&&<a className={styles.iconButton} href={receiptHref(row)} aria-label={`Download receipt for ${row.reference}`}><Icon name="download"/></a>}</td></tr>)}</tbody></table></div><p className={styles.footnote}>Showing {rows.length} of {payments.length} payments. Totals and statements follow these filters.</p></>:<div className={styles.empty}><Icon name="receipt"/><h3>{payments.length?'No matching payments':'No payments yet'}</h3><p>{payments.length?'Try another search, date or status.':'Your booking payment records and receipts will appear here.'}</p>{payments.length>0&&<button className={styles.button} onClick={()=>{setQ('');setMonth('');setStatus('')}}>Clear filters</button>}</div>}
  </section><aside className={styles.breakdown} aria-label="Selected payment breakdown"><h2><Icon name="receipt"/>Payment breakdown</h2>{selected?<><strong>Booking {selected.reference}</strong><p className={styles.vehicle}>{selected.vehicle}</p>{selected.test&&<small className={styles.testBadge}>Test payment</small>}<div className={styles.journey}><div><Icon name="pin"/><div><small>Collection</small><span>{selected.collection}</span></div></div><div><Icon name="pin"/><div><small>Delivery</small><span>{selected.delivery}</span></div></div></div><dl className={styles.amounts}><div><dt>Agreed booking total</dt><dd>{paymentMoney(selected.totalPence)}</dd></div><div><dt>Total paid</dt><dd>{paymentMoney(selected.paidPence)}</dd></div><div><dt>Refunds</dt><dd>{paymentMoney(selected.refundedPence)}</dd></div>{selected.refundedPence>0&&<div><dt>Net paid</dt><dd>{paymentMoney(selected.paidPence-selected.refundedPence)}</dd></div>}</dl><dl className={styles.meta}><div><dt>Paid on</dt><dd>{paymentDate(selected.paidAt)}</dd></div><div><dt>Payment status</dt><dd><Status value={selected.status}/></dd></div></dl>{selected.paidPence>0?<a className={`${styles.button} ${styles.orange}`} href={receiptHref(selected)}><Icon name="download"/>Download receipt (PDF)</a>:<p className={styles.footnote}>A receipt becomes available when a payment is recorded.</p>}<Link className={styles.button} href={bookingPaymentHref(selected)}>View booking</Link></>:<p className={styles.empty}>Select a payment to view its breakdown.</p>}</aside></div>
  <footer className={styles.footer}><span><Icon name="shield"/>Receipts and statements are available for your records.</span><span>Statement downloads: <a href={download('pdf')}>PDF</a> · <a href={download('csv')}>CSV</a></span></footer>
 </main>;
}
