'use client';
import {useState} from 'react';
import Link from 'next/link';
import {type CustomerPayment,filterPayments,paymentTotals,paymentMonth,paymentDate,paymentMoney,paymentLabel,paymentStatuses,bookingPaymentHref} from '@/lib/customer-payments';
import styles from './payments.module.css';
import {proceedsPeriod,inProceedsPeriod,periodDescription,periodQuery,londonDate} from '@/lib/payment-period';

function Icon({name}:{name:'download'|'card'|'refund'|'receipt'|'pin'|'shield'|'folder'|'calendar'|'car'|'list'|'van'|'coins'}){
 const paths={coins:'M21 5c0 2-4 3-9 3S3 7 3 5s4-3 9-3 9 1 9 3ZM3 5v14c0 2 4 3 9 3s9-1 9-3V5M3 10c0 2 4 3 9 3s9-1 9-3M3 15c0 2 4 3 9 3s9-1 9-3',van:'M2 17V4h13l7 7v6h-3M6 17h9M15 4v7h7M7 17a2 2 0 1 1-4 0 2 2 0 0 1 4 0m12 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0',folder:'M2 7V4h7l3 3h10v3M2 7h19l-4 13H2ZM2 7v13',calendar:'M4 4h16v18H4ZM8 2v5m8-5v5M4 10h16',car:'M3 15v-4l3-1 3-5h7l4 5 3 1v4h-3m-4 0H8M8 10h11M8 15a2 2 0 1 1-4 0 2 2 0 0 1 4 0m13 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0',list:'M8 5h14M8 12h14M8 19h14M2 5h1M2 12h1M2 19h1',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',card:'M3 4h18v16H3ZM3 9h18M6 15h4',refund:'m8 3-6 6 6 6M2 9h12a7 7 0 0 1 0 14',receipt:'M5 2h14v20l-3-2-4 2-4-2-3 2ZM8 7h8M8 11h8M8 15h5',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6Zm-5 10 3 3 6-6'};
 return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]}/></svg>;
}
function Status({value}:{value:string}){return <span className={`${styles.status} ${value==='PAID'?styles.paid:value.includes('REFUND')?styles.refunded:styles.pending}`}>{paymentLabel(value)}</span>}
const receiptHref=(row:CustomerPayment)=>`/api/customer/payments/download?bookingId=${encodeURIComponent(row.bookingId)}&format=pdf`;
export default function PaymentsView({payments}:{payments:CustomerPayment[]}){
 const [q,setQ]=useState(''),[month,setMonth]=useState(''),[status,setStatus]=useState(''),[selectedId,setSelectedId]=useState(payments[0]?.id||'');
 const [period,setPeriod]=useState(()=>proceedsPeriod({}));
 const [rangeError,setRangeError]=useState('');
 const years=Array.from(new Set([period.currentYear,...payments.map(p=>Number(londonDate(p.paidAt||p.createdAt).slice(0,4)))])).sort((a,b)=>b-a);
 const periodRows=payments.filter(p=>inProceedsPeriod({createdAt:p.paidAt||p.createdAt},period));
 const rows=filterPayments(periodRows,{q,month,status});
 const chooseYear=(year:number)=>{setPeriod(proceedsPeriod({year:String(year)}));setMonth('');setRangeError('')};
 const selected=rows.find(r=>r.id===selectedId)||rows[0];
 const totals=paymentTotals(rows);
 const months=Array.from(new Set(periodRows.flatMap(p=>p.paidAt?[paymentMonth(p.paidAt)]:[]))).sort().reverse();
 const download=(format:string)=>'/api/customer/payments/download?'+new URLSearchParams({format,q,month,status,...Object.fromEntries(periodQuery(period))}).toString();
 return <main className={styles.page}>
  <header className={styles.heading}><div><h1>Payments</h1><p>View your payments, refunds and booking receipts.</p></div><a className={styles.button} href={download('pdf')}><Icon name="download"/>Download statement</a></header>
  <section className={styles.yearSection} aria-label="Yearly statements">
   <div className={styles.yearHeading}><h2>Yearly statements</h2><details className={styles.dateRange}><summary><Icon name="calendar"/>Custom date range <span>⌄</span></summary><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);try{setPeriod(proceedsPeriod({start:String(form.get('start')),end:String(form.get('end'))}));setMonth('');setRangeError('');e.currentTarget.closest('details')?.removeAttribute('open')}catch(error){setRangeError((error as Error).message)}}}><label>Start date<input type="date" name="start" defaultValue={period.start} key={'start'+period.start} required/></label><label>End date<input type="date" name="end" defaultValue={period.end} key={'end'+period.end} required/></label>{rangeError&&<p role="alert">{rangeError}</p>}<button type="submit">Apply date range</button></form></details></div>
   <nav className={styles.yearCards} aria-label="Select payment year">{years.map(year=><button type="button" key={year} onClick={()=>chooseYear(year)} className={year===period.year?styles.selectedYear:undefined} aria-pressed={year===period.year}><Icon name="folder"/><div className={styles.yearIdentity}><strong>{year}</strong><span className={year===period.currentYear?styles.currentYear:styles.archivedYear}>{year===period.currentYear?'Current year':'Archived'}</span><small>1 January – 31 December {year}</small></div><small className={styles.yearCount}>{payments.filter(p=>Number(londonDate(p.paidAt||p.createdAt).slice(0,4))===year).length} payments</small><span className={styles.viewYear}>View year <span>→</span></span></button>)}</nav>
   <div className={styles.downloadBar}><div><strong>Showing {period.title}</strong><span>{periodDescription(period)}</span></div><div className={styles.downloadActions}><a href={download('pdf')}><Icon name="download"/>Download PDF</a><a href={download('csv')}><Icon name="download"/>Export CSV</a></div></div>
  </section>
  {payments.some(p=>p.test)&&<p className={styles.testNotice}>Test payments are labelled below. Their receipts are test records.</p>}
  <section className={styles.summary} aria-label="Payment totals for current filters">{([['Total paid',totals.paid,'coins'],['Refunded',totals.refunded,'refund'],['Net paid',totals.net,'receipt']] as const).map(([title,value,icon])=><article key={title}><Icon name={icon}/><div><span>{title}</span><strong>{paymentMoney(value)}</strong></div></article>)}</section>
  <div className={styles.columns}><section className={styles.history}><div className={styles.sectionHeading}><h2><Icon name="list"/>Payment history</h2><span aria-live="polite">{rows.length} payment{rows.length===1?'':'s'}</span></div>
   <div className={styles.filters}><input aria-label="Search booking or vehicle" placeholder="Search booking or vehicle" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Payment month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">All dates</option>{months.map(m=><option key={m} value={m}>{new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(m+'-01T00:00:00Z'))}</option>)}</select><select aria-label="Payment status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{paymentStatuses.map(s=><option key={s} value={s}>{paymentLabel(s)}</option>)}</select></div>
   {rows.length?<><div className={styles.tableScroll}><table><thead><tr><th>Booking / vehicle</th><th>Payment date</th><th>Amount paid</th><th>Status</th><th>Receipt</th></tr></thead><tbody>{rows.map(row=><tr key={row.id} className={selected?.id===row.id?styles.selected:''}><td><button className={styles.selectRow} onClick={()=>setSelectedId(row.id)} aria-pressed={selected?.id===row.id} aria-label={`View payment breakdown for ${row.reference}, ${row.vehicle}`}><Icon name={/van|transit|sprinter|motorhome/i.test(row.vehicle)?'van':'car'}/><strong>{row.reference}</strong><span>{row.vehicle}</span></button>{row.test&&<small className={styles.testBadge}>Test payment</small>}</td><td>{paymentDate(row.paidAt)}</td><td>{paymentMoney(row.paidPence,row.currency)}</td><td><Status value={row.status}/></td><td>{row.paidPence>0&&<a className={styles.iconButton} href={receiptHref(row)} aria-label={`Download receipt for ${row.reference}`}><Icon name="download"/></a>}</td></tr>)}</tbody></table></div><p className={styles.footnote}>Showing {rows.length} of {payments.length} payments. Totals and statements follow these filters.</p></>:<div className={styles.empty}><Icon name="receipt"/><h3>{payments.length?'No matching payments':'No payments yet'}</h3><p>{payments.length?'Try another search, date or status.':'Your booking payment records and receipts will appear here.'}</p>{payments.length>0&&<button className={styles.button} onClick={()=>{setQ('');setMonth('');setStatus('')}}>Clear filters</button>}</div>}
  </section><aside className={styles.breakdown} aria-label="Selected payment breakdown"><h2><Icon name="receipt"/>Payment breakdown</h2>{selected?<><small className={styles.bookingLabel}>Booking</small><strong>{selected.reference}</strong><p className={styles.vehicle}>{selected.vehicle}</p>{selected.test&&<small className={styles.testBadge}>Test payment</small>}<div className={styles.journey}><div><Icon name="pin"/><div><small>Collection</small><span>{selected.collection}</span></div></div><div><Icon name="pin"/><div><small>Delivery</small><span>{selected.delivery}</span></div></div></div><dl className={styles.amounts}><div><dt>Agreed booking total</dt><dd>{paymentMoney(selected.totalPence)}</dd></div><div><dt>Total paid</dt><dd>{paymentMoney(selected.paidPence)}</dd></div><div><dt>Refunds</dt><dd>{paymentMoney(selected.refundedPence)}</dd></div>{selected.refundedPence>0&&<div><dt>Net paid</dt><dd>{paymentMoney(selected.paidPence-selected.refundedPence)}</dd></div>}</dl><dl className={styles.meta}><div><dt>Paid on</dt><dd>{paymentDate(selected.paidAt)}</dd></div><div><dt>Payment status</dt><dd><Status value={selected.status}/></dd></div></dl>{selected.paidPence>0?<a className={`${styles.button} ${styles.orange}`} href={receiptHref(selected)}><Icon name="download"/>Download receipt (PDF)</a>:<p className={styles.footnote}>A receipt becomes available when a payment is recorded.</p>}<Link className={`${styles.button} ${styles.viewBooking}`} href={bookingPaymentHref(selected)}>View booking</Link></>:<p className={styles.empty}>Select a payment to view its breakdown.</p>}</aside></div>
  <p className={styles.archiveNote}>A new year starts automatically. Previous years stay available to view and download.</p>
  <footer className={styles.footer}><span><Icon name="shield"/>Receipts and statements are available for your records.</span><span>Statement downloads: <a href={download('pdf')}>PDF</a> · <a href={download('csv')}>CSV</a></span></footer>
 </main>;
}
