import './globals.css';
import './home-hero.css';
import './mobile-polish.css';
import './dashboard-polish.css';
import './admin-dashboard-polish.css';
import './admin-header-colors.css';
import './admin-verification-expander.css';
import './account-edit.css';
import './transporter-profile.css';
import './requote.css';
import './proof-of-delivery.css';
import './legacy-evidence-cleanup.css';
import './payment-secured-polish.css';
import './customer-booking-polish.css';
import './customer-card-expander.css';
import './transporter-card-expander.css';
import './completed-booking-polish.css';
import './transporter-completed-polish.css';
import './admin-payouts.css';
import './messages-polish.css';
import './notifications-polish.css';
import './manage-requests-polish.css';
import './transporter-reviews-polish.css';
import './transporter-verification-polish.css';
import './customer-quote-comparison.css';
import './customer-quote-request-details.css';
import './active-delivery-vehicle-details.css';
import './customer-completed-summary.css';
import Link from 'next/link';
import {currentUser} from '@/lib/auth';
import MessagesNavLink from '@/app/components/MessagesNavLink';
import NotificationNavLink from '@/app/components/NotificationNavLink';
import CustomerQuoteRequestNavigator from '@/app/components/CustomerQuoteRequestNavigator';
import CustomerVehicleTypeEnhancer from '@/app/components/CustomerVehicleTypeEnhancer';
import AgreedCollectionDateEnhancer from '@/app/components/AgreedCollectionDateEnhancer';
import TransporterRequoteEnhancer from '@/app/components/TransporterRequoteEnhancer';
import TransporterProfileEnhancer from '@/app/components/TransporterProfileEnhancer';
import TransporterDeliveredSummary from '@/app/components/TransporterDeliveredSummary';
import TransporterCancelDeliveryEnhancer from '@/app/components/TransporterCancelDeliveryEnhancer';
import TransporterProofOfDeliveryEnhancer from '@/app/components/TransporterProofOfDeliveryEnhancer';
import TransporterProofOfCollectionEnhancer from '@/app/components/TransporterProofOfCollectionEnhancer';
import CustomerProofOfCollectionEnhancer from '@/app/components/CustomerProofOfCollectionEnhancer';
import CustomerProofOfDeliveryEnhancer from '@/app/components/CustomerProofOfDeliveryEnhancer';
import CustomerCardExpander from '@/app/components/CustomerCardExpander';
import CustomerQuoteComparisonEnhancer from '@/app/components/CustomerQuoteComparisonEnhancer';
import CustomerQuoteRequestDetailsEnhancer from '@/app/components/CustomerQuoteRequestDetailsEnhancer';
import ActiveDeliveryVehicleDetails from '@/app/components/ActiveDeliveryVehicleDetails';
import CustomerCompletedCardSummary from '@/app/components/CustomerCompletedCardSummary';
import TransporterCardExpander from '@/app/components/TransporterCardExpander';
export const metadata={title:'DriveDrop',description:'UK vehicle transport marketplace'};
export default async function Layout({children}:{children:React.ReactNode}){const user=await currentUser();const dashboardHref=user?.role==='CUSTOMER'?'/customer':user?.role==='TRANSPORTER'?'/transporter':user?.role==='ADMIN'?'/admin':'/login';const reviewHref=user?.role==='TRANSPORTER'?'/transporter/reviews':user?.role==='ADMIN'?'/admin/review-disputes':null;const reviewLabel=user?.role==='TRANSPORTER'?'Reviews':user?.role==='ADMIN'?'Review moderation':null;return <html lang="en"><body><CustomerQuoteRequestNavigator/><AgreedCollectionDateEnhancer/><TransporterRequoteEnhancer/>{user?.role==='CUSTOMER'&&<><TransporterProfileEnhancer/><CustomerVehicleTypeEnhancer/><CustomerProofOfCollectionEnhancer/><CustomerProofOfDeliveryEnhancer/><CustomerCardExpander/><CustomerQuoteComparisonEnhancer/><CustomerQuoteRequestDetailsEnhancer/><ActiveDeliveryVehicleDetails/><CustomerCompletedCardSummary/></>}{user?.role==='TRANSPORTER'&&<><TransporterDeliveredSummary/><TransporterCancelDeliveryEnhancer/><TransporterProofOfCollectionEnhancer/><TransporterProofOfDeliveryEnhancer/><TransporterCardExpander/><ActiveDeliveryVehicleDetails/></>}<header className={`top${user?.role==='TRANSPORTER'?' transporterTop':user?.role==='CUSTOMER'?' customerTop':user?.role==='ADMIN'?' adminTop':!user?' guestTop':''}`}>{user?.role==='CUSTOMER'?<div className="customerPrimaryNav"><Link href="/" className="logo headerLogo" aria-label="DriveDrop home"><img src="/AC51EBEA-9552-47BB-92A0-E8D611539A71.png" alt="DriveDrop" /></Link><Link className="accountNavBtn" href="/account">Account</Link><Link className="btn orange customerDashboardBtn" href={dashboardHref}>Dashboard</Link><form action="/api/auth/logout" method="post"><button className="btn light" type="submit">Sign out</button></form></div>:user?.role==='TRANSPORTER'?<div className="transporterPrimaryNav"><Link href="/" className="logo headerLogo" aria-label="DriveDrop home"><img src="/AC51EBEA-9552-47BB-92A0-E8D611539A71.png" alt="DriveDrop" /></Link><Link className="btn light accountNavBtn" href="/account">Account</Link><Link className="btn orange transporterDashboardBtn" href={dashboardHref}>Dashboard</Link><form action="/api/auth/logout" method="post"><button className="btn light" type="submit">Sign out</button></form></div>:user?.role==='ADMIN'?<div className="adminPrimaryNav"><Link href="/" className="logo headerLogo adminHeaderLogo" aria-label="DriveDrop home"><img src="/AC51EBEA-9552-47BB-92A0-E8D611539A71.png" alt="DriveDrop" /></Link><span className="adminHeaderLabel"><small>DriveDrop</small><strong>Admin</strong></span></div>:!user?<div className="guestPrimaryNav"><Link href="/" className="logo headerLogo" aria-label="DriveDrop home"><img src="/AC51EBEA-9552-47BB-92A0-E8D611539A71.png" alt="DriveDrop" /></Link><Link className="btn light" href="/login?account=customer">Customer login</Link><Link className="btn orange" href="/login?account=transporter">Transporter login</Link></div>:<Link href="/" className="logo headerLogo" aria-label="DriveDrop home"><img src="/AC51EBEA-9552-47BB-92A0-E8D611539A71.png" alt="DriveDrop" /></Link>}<nav className={`nav${user?.role==='ADMIN'?' adminHeaderNav':''}`}>{user?<>{user.role==='TRANSPORTER'?<span className="transporterSecondaryNav"><Link href="/transporter/reviews">Reviews</Link><MessagesNavLink/><NotificationNavLink/></span>:user.role==='CUSTOMER'?<span className="customerSecondaryNav"><Link href="/customer/manage-requests">Manage requests</Link><MessagesNavLink/><NotificationNavLink/></span>:<><NotificationNavLink/>{reviewHref&&reviewLabel&&<Link className="adminHeaderLink" href={reviewHref}>{reviewLabel}</Link>}<Link className="btn light accountNavBtn adminHeaderButton" href="/account">Account</Link><Link className="btn orange adminHeaderButton adminDashboardButton" href={dashboardHref}>Dashboard</Link><form className="adminSignOutForm" action="/api/auth/logout" method="post"><button className="btn light adminHeaderButton adminSignOutButton" type="submit">Sign out</button></form></>}</>:null}</nav></header>{children}</body></html>}
