import Link from 'next/link';

const recent=[
  {vehicle:'BMW 3 Series',from:'Manchester, M1',to:'Bristol, BS1',price:'£210',icon:'🚗'},
  {vehicle:'Ford Transit',from:'Leeds, LS1',to:'London, E16',price:'£295',icon:'🚐'},
  {vehicle:'Porsche 911',from:'Birmingham, B1',to:'Edinburgh, EH1',price:'£465',icon:'🏎️'},
];

export default function Home(){return <main>
<section className="visualHero"><div className="heroOverlay"/><div className="visualHeroInner"><div className="marketHeroCopy"><span className="eyebrow">UK vehicle transport marketplace</span><h1>Move your vehicle with confidence</h1><p>Tell us what you need moved. Trusted transporters compete for your job, so you can compare prices, profiles and reviews before you book.</p><div className="heroBubbles"><span>✓ Free quotes</span><span>✓ No obligation</span><span>✓ UK-wide</span></div></div><div className="quotePanel floatingPanel"><div className="quotePanelHeader"><strong>Get vehicle transport quotes</strong><span>Takes about 60 seconds</span></div><form action="/register" className="quoteForm"><label>VEHICLE TYPE</label><select name="vehicleType" defaultValue="CAR"><option value="CAR">Car</option><option value="VAN">Van</option><option value="MOTORCYCLE">Motorcycle</option><option value="CLASSIC">Classic / prestige vehicle</option><option value="OTHER">Other vehicle</option></select><div className="quoteGrid"><div><label>COLLECTION POSTCODE</label><input name="collection" placeholder="e.g. M1 1AA" /></div><div><label>DELIVERY POSTCODE</label><input name="delivery" placeholder="e.g. BS1 1AA" /></div></div><button className="btn orange quoteCta">Get My Quotes</button><p className="quoteSmall">No payment required to request quotes.</p></form></div></div></section>
<section className="colourBand whiteBand"><div className="bubbleGrid"><div className="featureBubble"><div className="bubbleIcon">⚡</div><strong>Fast & easy</strong><span>One simple transport request</span></div><div className="featureBubble"><div className="bubbleIcon">🛡️</div><strong>Trusted transporters</strong><span>Verification and customer feedback</span></div><div className="featureBubble"><div className="bubbleIcon">💷</div><strong>Competitive quotes</strong><span>Compare transporters and prices</span></div><div className="featureBubble"><div className="bubbleIcon">🤝</div><strong>DriveDrop support</strong><span>A marketplace built for vehicles</span></div></div></section>
<section className="colourBand paleBand"><div className="sectionWrap centered"><span className="eyebrow dark">Simple from start to finish</span><h2>How DriveDrop works</h2><p className="sectionLead">Three clear steps from quote request to vehicle delivery.</p><div className="stepsGrid visualSteps"><article className="stepCard"><div className="stepIcon">📍</div><div className="stepNo">1</div><h3>Tell us the journey</h3><p>Add collection, delivery and vehicle details.</p></article><article className="stepCard"><div className="stepIcon">💬</div><div className="stepNo">2</div><h3>Compare your quotes</h3><p>Review price, profile, verification and feedback.</p></article><article className="stepCard"><div className="stepIcon">✅</div><div className="stepNo">3</div><h3>Choose and book</h3><p>Select your transporter and manage the delivery.</p></article></div><Link className="btn orange largeCta" href="/register">Request Vehicle Transport Quotes</Link></div></section>
<section className="photoSplit navyBand"><div className="sectionWrap splitGrid"><div className="splitPhoto"><img src="/drivedrop-uk-transporter.jpg" alt="UK vehicle transporter carrying cars"/></div><div className="splitCopy"><span className="eyebrow">Built around trust</span><h2>Know who is moving your vehicle</h2><p>DriveDrop is built specifically for vehicle movements, with transporter verification, insurance details, ratings and clear business profiles.</p><div className="pillList"><span>✓ DriveDrop Verified</span><span>✓ Insurance checks</span><span>✓ Customer reviews</span><span>✓ Vehicle specialisms</span></div></div></div></section>
<section className="colourBand orangeTint"><div className="sectionWrap trustGrid"><div><span className="eyebrow dark">Choose with confidence</span><h2>More than just a price</h2><p>Compare the transporter behind every quote and choose the service that feels right for your vehicle.</p></div><div className="verifiedCard liftedCard"><div className="verifiedTop"><div className="avatarTruck">🚛</div><div><strong>Northline Vehicle Transport</strong><span>DriveDrop Verified</span></div></div><div className="rating">★★★★★ <b>4.9</b></div><div className="verifiedStats"><div><b>248</b><span>Deliveries</span></div><div><b>11 yrs</b><span>Operating</span></div><div><b>UK-wide</b><span>Coverage</span></div></div><div className="verifiedTags"><span>Insured</span><span>Car transport</span><span>Non-runners</span></div></div></div></section>
<section className="photoBanner"><div className="photoBannerOverlay"/><div className="sectionWrap photoBannerContent"><span className="eyebrow">UK vehicle transport</span><h2>Cars, vans, classics and prestige vehicles</h2><p>From everyday vehicle moves to specialist transport, DriveDrop helps customers find the right transporter for the job.</p><Link className="btn orange largeCta" href="/register">Get Quotes</Link></div></section>
<section className="colourBand whiteBand"><div className="sectionWrap"><div className="sectionHeadingRow"><div><span className="eyebrow dark">Marketplace activity</span><h2>Recent vehicle deliveries</h2></div><Link href="/register">Get quotes →</Link></div><div className="recentGrid">{recent.map(x=><article className="deliveryCard visualDelivery" key={x.vehicle}><div className="vehicleBubble">{x.icon}</div><h3>{x.vehicle}</h3><div className="deliveryRoute"><span>● {x.from}</span><span>↓</span><span>● {x.to}</span></div><div className="deliveryPrice"><span>Example accepted quote</span><strong>{x.price}</strong></div></article>)}</div></div></section>
<section className="colourBand paleBlueBand"><div className="sectionWrap centered"><span className="eyebrow dark">Customer confidence</span><h2>Vehicle transport should feel straightforward</h2><div className="reviewGrid"><blockquote>“Clear quotes, clear transporter profiles and everything in one place.”<cite>Example customer experience</cite></blockquote><blockquote>“Seeing verification and reviews before booking makes a huge difference.”<cite>Example customer experience</cite></blockquote><blockquote>“Much easier than ringing around transport companies.”<cite>Example customer experience</cite></blockquote></div></div></section>
<section className="transporterCta"><div className="sectionWrap transporterCtaInner"><div><span className="eyebrow">For transport companies</span><h2>Find vehicle transport jobs that fit your routes</h2><p>Create your transporter profile, complete verification and quote on suitable customer jobs.</p></div><div><Link className="btn orange largeCta" href="/register?account=transporter">Join DriveDrop as a Transporter</Link><br/><Link className="textLink" href="/login?account=transporter">Already registered? Sign in</Link></div></div></section>
<footer className="siteFooter"><div className="sectionWrap footerGrid"><div><div className="logo footerLogo">Drive<span>Drop</span></div><p>UK vehicle transport, made simpler.</p><p className="footerSmall">DriveDrop is a marketplace connecting customers with independent vehicle transporters.</p></div><div><strong>Customers</strong><Link href="/register">Get quotes</Link><Link href="/login?account=customer">Customer login</Link></div><div><strong>Transporters</strong><Link href="/register?account=transporter">Join DriveDrop</Link><Link href="/login?account=transporter">Transporter login</Link></div><div><strong>Trust & legal</strong><span>Transporter verification</span><span>Secure booking</span><span>UK marketplace</span><Link href="/terms">Terms & Conditions</Link><Link href="/privacy">Privacy Policy</Link></div></div><div className="sectionWrap footerLegal"><p><strong>Marketplace fee:</strong> DriveDrop charges a 5% commission on the agreed transport price for bookings made through the marketplace.</p><p>© 2026 DriveDrop. All rights reserved.</p></div></footer>
</main>}
