import VerificationAdmin from '@/components/VerificationAdmin';
import AdminUserManagement from '@/components/AdminUserManagement';
import AdminDisputeManagement from '@/components/AdminDisputeManagement';
import AdminSectionSwitcher from '@/components/AdminSectionSwitcher';
import AdminBookingRecords from '@/components/AdminBookingRecords';
import AdminActionCentre from '@/components/AdminActionCentre';
import { currentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import Link from 'next/link';

export default async function Admin(){
 const u=await currentUser();
 if(!u||u.role!=='ADMIN')return <main className="shell dashboardShell"><div className="dashboardCard adminAccess"><div className="adminLock">🔐</div><span className="dashboardEyebrow dark">Restricted area</span><h1>Admin access</h1><p>Administrator authentication is required to access the DriveDrop Control Centre.</p><Link className="btn orange" href="/login">Sign in as administrator</Link></div></main>;
 const [users,jobs,quotes,bookings,userRows,disputeCount]=await Promise.all([
  prisma.user.count(),prisma.transportJob.count(),prisma.quote.count(),
  prisma.booking.findMany({include:{job:true,customer:true,transporter:true,trackingEvents:{orderBy:{createdAt:'asc'}},messages:{include:{sender:{select:{name:true}}},orderBy:{createdAt:'asc'}},evidence:{orderBy:{createdAt:'asc'}},review:true,disputes:{select:{id:true,status:true,reason:true,createdAt:true},orderBy:{createdAt:'desc'}},payment:{include:{events:{orderBy:{createdAt:'asc'}}}}},orderBy:{createdAt:'desc'}}),
  prisma.user.findMany({where:{role:{not:'ADMIN'}},select:{id:true,name:true,email:true,role:true,accountStatus:true,workRestricted:true,adminNote:true,createdAt:true,transporterVerification:{select:{status:true}},_count:{select:{customerJobs:true,transporterQuotes:true,customerBookings:true,transporterBookings:true}}},orderBy:{createdAt:'desc'}}),prisma.dispute.count()
 ]);
 const jobIds=bookings.map((b:any)=>b.jobId);const vehicleRows=jobIds.length?await prisma.$queryRawUnsafe<Array<{id:string;vehicleType:string|null}>>(`SELECT "id", "vehicleType" FROM "TransportJob" WHERE "id" IN (${jobIds.map((_:any,i:number)=>`$${i+1}`).join(',')})`,...jobIds):[];const vehicleTypes=new Map(vehicleRows.map(r=>[r.id,r.vehicleType]));
 const completed=bookings.filter((b:any)=>b.customerConfirmedAt).length;const gross=bookings.reduce((n:number,b:any)=>n+(b.payment?.paidPence||0),0);
 const adminUsers=userRows.map((x:any)=>({id:x.id,name:x.name,email:x.email,role:x.role,accountStatus:x.accountStatus,workRestricted:x.workRestricted,adminNote:x.adminNote,createdAt:x.createdAt.toISOString(),jobs:x._count.customerJobs,quotes:x._count.transporterQuotes,customerBookings:x._count.customerBookings,transporterBookings:x._count.transporterBookings,verificationStatus:x.transporterVerification?.status||null}));
 const transporterCount=userRows.filter((x:any)=>x.role==='TRANSPORTER').length;
 const pendingVerification=userRows.filter((x:any)=>x.role==='TRANSPORTER'&&x.transporterVerification?.status==='PENDING').length;
 const openDisputes=bookings.reduce((n:number,b:any)=>n+b.disputes.filter((d:any)=>d.status==='OPEN'||d.status==='UNDER_REVIEW').length,0);
 const readyPayouts=bookings.filter((b:any)=>b.payment?.payoutStatus==='READY').length;
 const blockedRows=readyPayouts?await prisma.$queryRaw<Array<{count:bigint}>>`SELECT COUNT(*)::bigint AS count FROM "BookingPayment" p JOIN "Booking" b ON b.id=p."bookingId" LEFT JOIN "TransporterPayoutDetails" d ON d."userId"=b."transporterId" WHERE p."payoutStatus"='READY' AND d.id IS NULL`:[];
 const blockedPayouts=Number(blockedRows[0]?.count||0);
 const clientBookings=bookings.map((b:any)=>({...b,job:{...b.job,vehicleType:vehicleTypes.get(b.jobId)||null},createdAt:b.createdAt?.toISOString?.()||b.createdAt,customerConfirmedAt:b.customerConfirmedAt?.toISOString?.()||b.customerConfirmedAt,trackingEvents:b.trackingEvents.map((e:any)=>({...e,createdAt:e.createdAt.toISOString()})),messages:b.messages.map((m:any)=>({...m,createdAt:m.createdAt?.toISOString?.()||m.createdAt})),evidence:b.evidence.map((e:any)=>({...e,createdAt:e.createdAt?.toISOString?.()||e.createdAt})),disputes:b.disputes.map((d:any)=>({...d,createdAt:d.createdAt?.toISOString?.()||d.createdAt})),payment:b.payment?{...b.payment,createdAt:b.payment.createdAt?.toISOString?.()||b.payment.createdAt,updatedAt:b.payment.updatedAt?.toISOString?.()||b.payment.updatedAt,events:b.payment.events.map((e:any)=>({...e,createdAt:e.createdAt.toISOString()}))}:null}));
 const userSection=<><div className="dashboardSectionHeading"><div><span className="dashboardEyebrow dark">Accounts</span><h2>User management</h2></div><span>{adminUsers.length} customer & transporter accounts</span></div><AdminUserManagement users={adminUsers}/></>;
 const verificationSection=<><div className="dashboardSectionHeading"><div><span className="dashboardEyebrow dark">Compliance</span><h2>Transporter verification</h2></div><span>Review business and insurance documents</span></div><div className="adminVerificationWrap"><VerificationAdmin/></div></>;
 const disputeSection=<><div className="dashboardSectionHeading"><div><span className="dashboardEyebrow dark">Customer protection</span><h2>Dispute management</h2></div><span>Review active booking disputes and protected payouts</span></div><AdminDisputeManagement/></>;
 const operationsSection=<><div className="dashboardSectionHeading"><div><span className="dashboardEyebrow dark">Marketplace operations</span><h2>Bookings & deliveries</h2></div><span>{bookings.length} total</span></div><AdminBookingRecords bookings={clientBookings}/></>;
 return <main className="shell dashboardShell adminShell"><header className="dashboardHero adminHero"><div><span className="dashboardEyebrow">DriveDrop operations</span><h1>Control Centre</h1><p>Monitor marketplace activity, user accounts, transporter compliance, live deliveries and platform payments.</p></div><div className="adminHeroBadge" style={{display:'flex',flexDirection:'column',alignItems:'center',gap:8,padding:'18px 24px',border:'1px solid rgba(255,255,255,.34)',borderRadius:18,background:'rgba(255,255,255,.10)',boxShadow:'0 12px 28px rgba(0,0,0,.10)',minWidth:150}}><span style={{display:'block'}}>Platform overview</span><strong style={{display:'block'}}>{bookings.length}</strong><small style={{display:'block'}}>Total bookings</small></div></header><section className="adminStats"><div className="adminStat"><span>👥</span><div><strong>{users}</strong><small>Registered users</small></div></div><div className="adminStat"><span>🚗</span><div><strong>{jobs}</strong><small>Transport jobs</small></div></div><div className="adminStat"><span>💬</span><div><strong>{quotes}</strong><small>Quotes submitted</small></div></div><div className="adminStat"><span>✓</span><div><strong>{completed}</strong><small>Completed deliveries</small></div></div><div className="adminStat"><span>£</span><div><strong>£{(gross/100).toFixed(0)}</strong><small>Payments received</small></div></div></section><AdminActionCentre pendingVerification={pendingVerification} openDisputes={openDisputes} readyPayouts={readyPayouts} blockedPayouts={blockedPayouts}/><AdminSectionSwitcher userCount={adminUsers.length} transporterCount={transporterCount} disputeCount={disputeCount} userSection={userSection} verificationSection={verificationSection} disputeSection={disputeSection} operationsSection={operationsSection}/></main>;
}
