'use client';
import {useMemo,useState} from 'react';
import {useRouter} from 'next/navigation';

type UserRow={id:string;name:string;email:string;role:string;accountStatus:string;workRestricted:boolean;adminNote:string|null;createdAt:string;jobs:number;quotes:number;customerBookings:number;transporterBookings:number;verificationStatus:string|null};
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());

export default function AdminUserManagement({users}:{users:UserRow[]}){
 const router=useRouter();const[q,setQ]=useState('');const[busy,setBusy]=useState<string|null>(null);const[notes,setNotes]=useState<Record<string,string>>(()=>Object.fromEntries(users.map(u=>[u.id,u.adminNote||''])));
 const shown=useMemo(()=>{const x=q.trim().toLowerCase();return !x?users:users.filter(u=>[u.name,u.email,u.role,u.accountStatus].some(v=>v.toLowerCase().includes(x)))},[q,users]);
 async function act(id:string,action:string){if(action==='DELETE'&&!confirm('Remove this account? This disables access but preserves completed booking records.'))return;setBusy(id+action);const r=await fetch(`/api/admin/users/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({action,note:notes[id]})});const d=await r.json().catch(()=>({}));setBusy(null);if(!r.ok)return alert(d.error||'Unable to update account');router.refresh();}
 return <section className="dashboardCard"><div className="panelHeading"><div><span className="panelIcon">👥</span><div><h2>User management</h2><p>Search accounts, review activity and control customer or transporter access.</p></div></div></div><div className="field"><label>SEARCH USERS</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Name, email, role or status"/></div><div style={{display:'grid',gap:14}}>{shown.map(u=><article key={u.id} className="infoPanel"><div className="bookingTop"><div><div className="statusGroup"><span className="statusPill">{label(u.role)}</span><span className={`statusPill ${u.accountStatus==='ACTIVE'?'successPill':''}`}>{label(u.accountStatus)}</span>{u.role==='TRANSPORTER'&&u.workRestricted&&<span className="statusPill">Work restricted</span>}</div><h3 style={{marginBottom:4}}>{u.name}</h3><p className="bookingPartner">{u.email} · Joined {new Date(u.createdAt).toLocaleDateString('en-GB')}</p></div><div className="paymentMini"><span>Activity</span><strong>{u.role==='CUSTOMER'?u.jobs:u.quotes}</strong><small>{u.role==='CUSTOMER'?'Quote requests':'Quotes submitted'}</small></div></div><div className="infoRow"><span>Bookings</span><b>{u.role==='CUSTOMER'?u.customerBookings:u.transporterBookings}</b></div>{u.role==='TRANSPORTER'&&<div className="infoRow"><span>Verification</span><b>{u.verificationStatus?label(u.verificationStatus):'Not started'}</b></div>}<div className="field"><label>INTERNAL ADMIN NOTE</label><textarea value={notes[u.id]||''} onChange={e=>setNotes(n=>({...n,[u.id]:e.target.value}))} placeholder="Visible to admins only"/></div><div className="actionButtons"><button className="btn light" disabled={!!busy} onClick={()=>act(u.id,'SAVE_NOTE')}>Save note</button>{u.accountStatus==='ACTIVE'?<button className="btn navy" disabled={!!busy} onClick={()=>act(u.id,'SUSPEND')}>Suspend account</button>:u.accountStatus==='SUSPENDED'?<button className="btn orange" disabled={!!busy} onClick={()=>act(u.id,'REACTIVATE')}>Reactivate account</button>:null}{u.role==='TRANSPORTER'&&u.accountStatus!=='DELETED'&&(u.workRestricted?<button className="btn orange" disabled={!!busy} onClick={()=>act(u.id,'RESTORE_WORK')}>Restore work access</button>:<button className="btn light" disabled={!!busy} onClick={()=>act(u.id,'RESTRICT_WORK')}>Restrict new work</button>)}{u.accountStatus!=='DELETED'&&<button className="btn light" disabled={!!busy} onClick={()=>act(u.id,'DELETE')}>Remove account</button>}</div></article>)}</div>{shown.length===0&&<div className="emptyState"><p>No matching users.</p></div>}</section>
}
