import Link from 'next/link';

export default function TermsPage(){return <main className="shell"><div className="card" style={{maxWidth:900,margin:'20px auto'}}><span className="eyebrow dark">DriveDrop legal</span><h1>Terms & Conditions</h1><p className="muted">Last updated: 27 August 2026</p><p>These terms govern use of the DriveDrop vehicle transport marketplace by customers and transporters in the United Kingdom. By creating an account, requesting or providing a quote, or booking through DriveDrop, you agree to these terms.</p>
<h2>1. The DriveDrop marketplace</h2><p>DriveDrop provides an online marketplace that allows customers seeking vehicle transportation to connect with independent vehicle transport businesses and drivers. Unless expressly stated otherwise, DriveDrop is not the transporter, carrier or owner of vehicles used to perform a delivery. The transport contract is formed between the customer and the transporter whose quote is accepted.</p>
<h2>2. Customer responsibilities</h2><p>Customers must provide accurate collection, delivery and vehicle information, including whether a vehicle is roadworthy or a non-runner and any condition that may affect loading or transport. Customers must ensure lawful access to the vehicle and collection/delivery locations and must not request transport of stolen, unlawfully held or prohibited property.</p>
<h2>3. Transporter responsibilities</h2><p>Transporters operate as independent businesses and are responsible for maintaining all licences, registrations, permissions and insurance required for the services they provide. Transporters must provide accurate business and insurance information, use suitable and roadworthy transport equipment, comply with applicable road transport and safety law, and perform accepted bookings with reasonable care and skill.</p>
<h2>4. Quotes and bookings</h2><p>Transporter quotes should clearly represent the price and service offered. A booking is created when a customer accepts a quote through DriveDrop. Any agreed collection-date changes should be recorded through the platform. Neither party should deliberately circumvent DriveDrop to avoid marketplace charges on work introduced through DriveDrop.</p>
<h2>5. DriveDrop commission</h2><p><strong>DriveDrop charges a 5% commission on the agreed transport price for bookings made through the marketplace.</strong> The applicable fee will be shown as part of the booking/payment information. Unless DriveDrop expressly states otherwise at checkout, the commission is calculated as 5% of the agreed vehicle transport charge, excluding any separately identified refund or adjustment. Transporters agree that the applicable commission may be deducted or accounted for through the DriveDrop payment process.</p>
<h2>6. Payments</h2><p>Payments made through DriveDrop must follow the payment process displayed for the booking. Users must not misuse payment services, initiate fraudulent transactions or attempt to avoid legitimate marketplace charges. Refunds, payment holds and transporter payouts may be delayed where reasonably necessary to investigate cancellations, disputes, suspected fraud or delivery issues.</p>
<h2>7. Cancellations</h2><p>Customers may cancel eligible transport requests and transporters may cancel eligible deliveries using the controls provided by DriveDrop. Cancellation rights, refunds and any sums payable will depend on the stage of the booking, work already performed and applicable consumer law. A transporter should notify the customer promptly if unable to complete an accepted delivery.</p>
<h2>8. Vehicle condition, collection and delivery</h2><p>The parties should inspect the vehicle at collection and delivery and retain appropriate condition evidence. Customers should remove valuables and personal possessions unless expressly agreed with the transporter. Transporters must take reasonable care of vehicles while they are under their control and promptly report loss, damage, delay or other material incidents.</p>
<h2>9. Insurance and verification</h2><p>DriveDrop may request business, identity, insurance or other verification documents from transporters and may approve, reject, suspend or re-check verification. Verification is intended to support marketplace trust but does not replace a customer's own assessment of a transporter or guarantee future performance, insurance coverage or regulatory compliance.</p>
<h2>10. Reviews and communications</h2><p>Reviews and platform communications must be genuine, lawful and relevant. Users must not post threatening, abusive, discriminatory, fraudulent or knowingly false material. DriveDrop may moderate or remove content where reasonably necessary to protect users or the marketplace.</p>
<h2>11. Account suspension and removal</h2><p>DriveDrop may restrict, suspend or remove an account where there is suspected fraud, unsafe conduct, serious or repeated breach of these terms, invalid verification, non-payment of applicable charges, misuse of the platform or a reasonable need to protect users. Relevant booking, payment and audit records may be retained where legally or operationally necessary.</p>
<h2>12. Disputes</h2><p>Customers and transporters should first try to resolve service issues using the booking records and evidence available through DriveDrop. DriveDrop may assist with marketplace disputes but does not replace the legal rights or remedies of either party.</p>
<h2>13. Liability</h2><p>Nothing in these terms excludes or limits liability where it would be unlawful to do so, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation. Subject to applicable law, DriveDrop is not responsible for the independent acts or omissions of a transporter or customer and does not guarantee that a particular quote, booking or delivery will be available or completed.</p>
<h2>14. Consumer rights</h2><p>Nothing in these terms removes statutory rights that a consumer cannot lawfully waive. Where consumer protection law gives a customer additional cancellation, refund or service rights, those rights continue to apply.</p>
<h2>15. Changes to these terms</h2><p>DriveDrop may update these terms from time to time. Material changes will apply from the date stated in the updated terms and, where required, users will be given appropriate notice.</p>
<h2>16. Governing law</h2><p>These terms are governed by the laws applicable in the United Kingdom jurisdiction in which the relevant user is based, subject to any mandatory consumer rights concerning jurisdiction and applicable law.</p>
<p style={{marginTop:32}}><strong>Important:</strong> These marketplace terms are a practical starting point for DriveDrop and should be reviewed by a UK solicitor before the service accepts live customer payments or commercial bookings.</p><Link className="btn navy" href="/">Back to DriveDrop</Link></div></main>}
