'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';

type Item={id:string;rating:number;body:string|null;createdAt:string;customerName:string;transporterName:string;vehicleMake:string;vehicleModel:string;transporterResponse:string|null;disputeReason:string|null;disputeDetails:string|null;disputedAt:string|null};
const stars=(n:number)=>'★'.repeat(n)+'☆'.repeat(5-n);

export default function ReviewDisputes(){
 const[items,setItems]=useState<Item[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[expanded,setExpanded]=useState<string|null>(null);
 async function load(){const r=await fetch('/api/admin/review-disputes',{cache:'no-store'});if(r.ok)setItems(await r.json());setLoading(false)}
 useEffect(()=>{load()},[]);
 async function resolve(reviewId:string,action:'KEEP'|'HIDE'|'REJECT'){const promptText=action==='KEEP'?'Explain why the review will remain visible:':action==='HIDE'?'Explain why this review is being hidden:':'Explain why the review dispute is being rejected/closed:';const note=prompt(promptText);if(!note?.trim())return;setMessage('');const r=await fetch('/api/admin/review-disputes',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({reviewId,action,note})});const d=await r.json().catch(()=>({}));if(!r.ok)return setMessage(d.error||'Unable to resolve review dispute');setMessage(action==='KEEP'?'Review kept visible and dispute closed.':action==='HIDE'?'Review hidden and removed from the transporter rating.':'Review dispute rejected and closed with an explanation.');if(expanded===reviewId)setExpanded(null);await load()}
 return <main className="shell dashboardShell reviewModerationPage"><Link className="backLink" href="/admin">← Back to Admin Control Centre</Link><header className="dashboardHero adminHero"><div><span className="dashboardEyebrow">Review moderation</span><h1>Customer review disputes</h1><p>Review transporter challenges to customer feedback and decide whether each verified review should remain visible.</p></div><div className="adminHeroBadge"><span>Awaiting review</span><strong>{items.length}</strong><small>Open review disputes</small></div></header>{message&&<div className="formNotice successNotice">{message}</div>}{loading?<div className="dashboardCard">Loading review disputes…</div>:items.length===0?<div className="dashboardCard emptyState"><div>✓</div><h3>No review disputes awaiting moderation</h3><p>New transporter review disputes will appear here.</p></div>:<div className="reviewModerationList">{items.map(i=>{const open=expanded===i.id;return <article className={`dashboardCard reviewModerationCard ${open?'isExpanded':''}`} key={i.id}><button type="button" className="reviewModerationSummary" onClick={()=>setExpanded(open?null:i.id)} aria-expanded={open}><div className="reviewModerationIdentity"><div className="statusGroup"><span className="statusPill">Under review</span><span className="statusPill">{i.rating}/5</span></div><strong>{i.transporterName}</strong><small>Customer · {i.customerName} · {i.vehicleMake} {i.vehicleModel}</small></div><div className="reviewModerationQuick"><span><small>Rating</small><b>{stars(i.rating)}</b></span><span><small>Reason</small><b>{i.disputeReason||'Not provided'}</b></span><span><small>Submitted</small><b>{i.disputedAt?new Date(i.disputedAt).toLocaleDateString('en-GB'):new Date(i.createdAt).toLocaleDateString('en-GB')}</b></span></div><span className="adminUserChevron">{open?'−':'+'}</span></button>{open&&<div className="reviewModerationExpanded"><div className="bookingColumns"><section><h3>Customer review</h3><div className="infoPanel"><p style={{margin:0}}>{i.body||'No written comment was provided.'}</p></div>{i.transporterResponse&&<><h3 style={{marginTop:16}}>Transporter public response</h3><div className="infoPanel"><p style={{margin:0}}>{i.transporterResponse}</p></div></>}</section><section><h3>Transporter dispute</h3><div className="infoPanel"><div className="infoRow"><span>Reason</span><b>{i.disputeReason}</b></div>{i.disputeDetails&&<p className="muted">{i.disputeDetails}</p>}{i.disputedAt&&<small className="muted">Submitted {new Date(i.disputedAt).toLocaleString('en-GB')}</small>}</div><div className="actionButtons reviewModerationActions"><button className="btn navy" onClick={()=>resolve(i.id,'KEEP')}>Keep review</button><button className="btn light" onClick={()=>resolve(i.id,'REJECT')}>Reject dispute</button><button className="btn orange" onClick={()=>resolve(i.id,'HIDE')}>Hide review</button></div></section></div></div>}</article>})}</div>}</main>
}
