import Link from 'next/link';

export default function PrivacyPage(){return <main className="shell"><div className="card" style={{maxWidth:900,margin:'20px auto'}}><span className="eyebrow dark">DriveDrop legal</span><h1>Privacy Policy</h1><p className="muted">Last updated: 27 August 2026</p><p>This privacy policy explains how DriveDrop handles personal information when customers and transporters use the DriveDrop vehicle transport marketplace in the United Kingdom.</p>
<h2>1. Information we may collect</h2><p>We may collect information you provide when creating or using an account, including your name, contact details, account type, vehicle transport requests, collection and delivery information, quotes, bookings, messages and support communications. For transporter accounts, we may also process business, verification and insurance information.</p>
<h2>2. How we use information</h2><p>We may use personal information to provide and operate the marketplace, create and manage accounts, connect customers with transporters, process transport requests and bookings, support verification, provide customer support, prevent fraud and misuse, maintain platform security, improve DriveDrop and comply with legal obligations.</p>
<h2>3. Information shared through the marketplace</h2><p>Information necessary to arrange a vehicle movement may be shared between the relevant customer and transporter. Transporter profile information, ratings, reviews and verification indicators may be displayed to customers where appropriate. We do not intend to make private account information public unless it is required for a marketplace feature or the user has chosen to provide it publicly.</p>
<h2>4. Service providers</h2><p>DriveDrop may use trusted service providers to host and operate the platform, store data, provide authentication, process payments, deliver communications, monitor security and provide other technical services. These providers may process information only as needed to provide their services and subject to appropriate contractual and legal safeguards.</p>
<h2>5. Payments</h2><p>Where payment functionality is provided, payment information may be processed by a specialist payment provider. DriveDrop may receive transaction details and payment status information needed to manage bookings, marketplace commission, refunds, disputes and transporter payouts.</p>
<h2>6. Legal bases</h2><p>Depending on the circumstances, DriveDrop may process personal information because it is necessary to provide requested services or perform a contract, because of a legitimate business interest such as operating and securing the marketplace, because of a legal obligation, or because consent has been provided where consent is required.</p>
<h2>7. Data retention</h2><p>We aim to retain personal information only for as long as reasonably necessary for the purposes for which it was collected, including providing the marketplace, maintaining booking and transaction records, resolving disputes, preventing fraud and meeting legal, tax, accounting or regulatory requirements.</p>
<h2>8. Security</h2><p>DriveDrop uses reasonable technical and organisational measures intended to protect personal information. No online service can guarantee absolute security, and users are responsible for keeping their login details secure and notifying DriveDrop if they believe their account has been compromised.</p>
<h2>9. Your data protection rights</h2><p>Depending on applicable UK data protection law and the circumstances, you may have rights concerning your personal information, including rights to request access, correction, deletion, restriction or portability, and to object to certain processing. Where processing is based on consent, consent may generally be withdrawn without affecting earlier lawful processing.</p>
<h2>10. Cookies and similar technology</h2><p>DriveDrop may use cookies or similar technologies that are necessary for authentication, security and operation of the website. If optional analytics, advertising or other non-essential technologies are introduced, appropriate information and consent controls should be provided where required by law.</p>
<h2>11. Changes to this policy</h2><p>This policy may be updated as DriveDrop develops. Material changes will be reflected by updating the date shown above and, where required, providing additional notice.</p>
<h2>12. Contact</h2><p>DriveDrop contact details for privacy enquiries will be added before the marketplace begins accepting live commercial bookings.</p>
<p style={{marginTop:32}}><strong>Important:</strong> This privacy policy is a practical starting point for DriveDrop and should be reviewed alongside the platform's actual data flows and by an appropriate UK legal or data-protection professional before live launch.</p><Link className="btn navy" href="/">Back to DriveDrop</Link></div></main>}
