import {NextResponse} from 'next/server';
import {prisma} from '@/lib/prisma';
import {currentUser} from '@/lib/auth';
import {disputesEnabled} from '@/lib/features';
import {sendTransactionalEmailSafely} from '@/lib/email';
import {createNotificationSafely} from '@/lib/notifications';
import {financeConfig} from '@/lib/finance';
import {z} from 'zod';

const Review=z.object({disputeId:z.string().min(1),status:z.enum(['UNDER_REVIEW','RESOLVED','CLOSED']),resolution:z.enum(['REFUND_CUSTOMER','PARTIAL_REFUND','RELEASE_PAYOUT','NO_ACTION','OTHER']).optional(),resolutionNote:z.string().trim().max(2000).optional(),refundAmountPence:z.number().int().positive().optional()});
const disabled=()=>NextResponse.json({error:'Disputes are not enabled in this environment'},{status:404});
const resolutionLabel=(r?:string)=>({REFUND_CUSTOMER:'Refund customer',PARTIAL_REFUND:'Partial refund',RELEASE_PAYOUT:'Release transporter payout',NO_ACTION:'No action',OTHER:'Other resolution'}[r||'']||'Resolved');

export async function GET(){if(!disputesEnabled())return disabled();const u=await currentUser();if(!u||u.role!=='ADMIN')return NextResponse.json({error:'Admin access required'},{status:403});const disputes=await prisma.dispute.findMany({include:{raisedBy:{select:{id:true,name:true,email:true,role:true}},booking:{include:{job:true,customer:{select:{id:true,name:true,email:true}},transporter:{select:{id:true,name:true,email:true}},payment:true,evidence:{select:{id:true,type:true,note:true,createdAt:true},orderBy:{createdAt:'asc'}}}}},orderBy:[{status:'asc'},{createdAt:'desc'}]});const jobIds=[...new Set(disputes.map((d:any)=>d.booking?.job?.id).filter(Boolean))];const vehicleRows=jobIds.length?await prisma.$queryRawUnsafe<Array<{id:string;vehicleType:string|null}>>(`SELECT "id", "vehicleType" FROM "TransportJob" WHERE "id" IN (${jobIds.map((_:any,i:number)=>`$${i+1}`).join(',')})`,...jobIds):[];const vehicleTypes=new Map(vehicleRows.map(r=>[r.id,r.vehicleType]));return NextResponse.json(disputes.map((d:any)=>({...d,booking:d.booking?{...d.booking,job:{...d.booking.job,vehicleType:vehicleTypes.get(d.booking.job.id)||null}}:d.booking})))}

export async function PATCH(r:Request){
 if(!disputesEnabled())return disabled();const u=await currentUser();if(!u||u.role!=='ADMIN')return NextResponse.json({error:'Admin access required'},{status:403});const parsed=Review.safeParse(await r.json());if(!parsed.success)return NextResponse.json({error:'Invalid dispute review'},{status:400});const d=parsed.data;if(d.status==='RESOLVED'&&!d.resolution)return NextResponse.json({error:'A resolution is required when resolving a dispute'},{status:400});
 try{
  const result=await prisma.$transaction(async(tx:any)=>{
   const dispute=await tx.dispute.findUniqueOrThrow({where:{id:d.disputeId},include:{booking:{include:{payment:true,job:true,customer:{select:{id:true,name:true,email:true}},transporter:{select:{id:true,name:true,email:true}}}}}});const payment=dispute.booking.payment;let refundAmountPence=0;
   if(d.status==='UNDER_REVIEW'&&payment&&payment.payoutStatus!=='PAID'&&payment.payoutStatus!=='CANCELLED'&&payment.payoutStatus!=='HELD')await tx.bookingPayment.update({where:{id:payment.id},data:{payoutStatus:'HELD'}});
   if(d.status==='RESOLVED'&&d.resolution==='RELEASE_PAYOUT'&&payment){if(payment.status!=='PAID')throw new Error('Customer payment must be paid before payout can be released');if(dispute.booking.status!=='DELIVERED'||!dispute.booking.customerConfirmedAt)throw new Error('Delivery and customer confirmation are required before payout can be released');if(payment.payoutStatus==='PAID')throw new Error('Payout has already been released');await tx.bookingPayment.update({where:{id:payment.id},data:{payoutStatus:'READY'}})}
   if(d.status==='RESOLVED'&&d.resolution==='NO_ACTION'&&payment&&payment.payoutStatus==='HELD'){const eligible=payment.status==='PAID'&&dispute.booking.status==='DELIVERED'&&!!dispute.booking.customerConfirmedAt;await tx.bookingPayment.update({where:{id:payment.id},data:{payoutStatus:eligible?'READY':'NOT_READY'}})}
   if(d.status==='RESOLVED'&&['REFUND_CUSTOMER','PARTIAL_REFUND'].includes(d.resolution||'')){
    if(!payment)throw new Error('No payment exists for this booking');if(payment.payoutStatus==='PAID')throw new Error('Cannot refund after transporter payout has been released');if(payment.paidPence<=0)throw new Error('No captured customer payment to refund');const refundable=payment.paidPence-payment.refundedPence;if(refundable<=0)throw new Error('Customer payment has already been fully refunded');
    refundAmountPence=d.resolution==='REFUND_CUSTOMER'?refundable:(d.refundAmountPence||0);if(d.resolution==='PARTIAL_REFUND'&&refundAmountPence<=0)throw new Error('Enter a partial refund amount');if(refundAmountPence>refundable)throw new Error('Refund exceeds the remaining paid balance');if(d.resolution==='PARTIAL_REFUND'&&refundAmountPence===refundable)throw new Error('Use Refund Customer for a full remaining refund');const refunded=payment.refundedPence+refundAmountPence;const paymentStatus=refunded===payment.paidPence?'REFUNDED':'PARTIALLY_REFUNDED';const eligibleAfterPartial=d.resolution==='PARTIAL_REFUND'&&dispute.booking.status==='DELIVERED'&&!!dispute.booking.customerConfirmedAt;const nextPayoutStatus=d.resolution==='REFUND_CUSTOMER'?'CANCELLED':eligibleAfterPartial?'READY':'NOT_READY';const remainingTransportValue=Math.max(0,payment.transportValuePence-refunded);const nextPlatformFee=d.resolution==='REFUND_CUSTOMER'?0:Math.round(remainingTransportValue*financeConfig.commissionPercent/100);const nextTransporterProceeds=Math.max(0,remainingTransportValue-nextPlatformFee);
    await tx.bookingPayment.update({where:{id:payment.id},data:{refundedPence:refunded,status:paymentStatus,payoutStatus:nextPayoutStatus,platformFeePence:nextPlatformFee,transporterProceedsPence:nextTransporterProceeds}});await tx.financeEvent.create({data:{paymentId:payment.id,type:'REFUND_CREATED',amountPence:refundAmountPence,actorId:u.id,note:`Dispute resolution refund — ${d.resolution==='REFUND_CUSTOMER'?'full':'partial'}`}});
   }
   const updated=await tx.dispute.update({where:{id:d.disputeId},data:{status:d.status,resolution:d.resolution,resolutionNote:d.resolutionNote,reviewerId:u.id,reviewedAt:new Date()}});return{updated,booking:dispute.booking,previousStatus:dispute.status,refundAmountPence};
  });
  const b=result.booking;const vehicle=[b.job.vehicleMake,b.job.vehicleModel].filter(Boolean).join(' ').replace(/\s+/g,' ').trim()||'vehicle';const customerPath='/customer?view=bookings';const transporterPath='/transporter?view=deliveries';
  if(d.status==='UNDER_REVIEW'&&result.previousStatus!=='UNDER_REVIEW')await Promise.all([createNotificationSafely({userId:b.customer.id,type:'DISPUTE',title:'Dispute under review',body:`DriveDrop is now reviewing the dispute for the ${vehicle}.`,href:customerPath}),createNotificationSafely({userId:b.transporter.id,type:'DISPUTE',title:'Dispute under review',body:`DriveDrop is now reviewing the dispute for the ${vehicle}. Any unreleased payout remains protected.`,href:transporterPath})]);
  if(d.status==='RESOLVED'&&result.previousStatus!=='RESOLVED'){const outcome=resolutionLabel(d.resolution);const refund=result.refundAmountPence>0?` Refund recorded: £${(result.refundAmountPence/100).toFixed(2)}.`:'';const note=d.resolutionNote?.trim()?` DriveDrop note: ${d.resolutionNote.trim()}`:'';await Promise.all([createNotificationSafely({userId:b.customer.id,type:'DISPUTE',title:'Dispute resolved',body:`${vehicle}: ${outcome}.${refund}${note}`,href:customerPath}),createNotificationSafely({userId:b.transporter.id,type:'DISPUTE',title:'Dispute resolved',body:`${vehicle}: ${outcome}.${refund}${note}`,href:transporterPath}),sendTransactionalEmailSafely({to:b.customer.email,subject:`DriveDrop dispute resolved — ${vehicle}`,heading:'Dispute resolved',preheader:`DriveDrop has resolved the dispute for your ${vehicle} booking.`,body:`Hi ${b.customer.name?.trim()||'there'},\n\nDriveDrop has completed its review of the dispute regarding the ${vehicle}.\n\nResolution: ${outcome}${result.refundAmountPence>0?`\n\nRefund recorded: £${(result.refundAmountPence/100).toFixed(2)}`:''}${d.resolutionNote?.trim()?`\n\nDriveDrop review note: ${d.resolutionNote.trim()}`:''}\n\nYou can view the latest booking and dispute status in your DriveDrop account.`,ctaLabel:'View booking',ctaPath:customerPath}),sendTransactionalEmailSafely({to:b.transporter.email,subject:`DriveDrop dispute resolved — ${vehicle}`,heading:'Dispute resolved',preheader:`DriveDrop has resolved the dispute for the ${vehicle} booking.`,body:`Hi ${b.transporter.name?.trim()||'there'},\n\nDriveDrop has completed its review of the dispute regarding the ${vehicle}.\n\nResolution: ${outcome}${result.refundAmountPence>0?`\n\nRefund recorded: £${(result.refundAmountPence/100).toFixed(2)}`:''}${d.resolutionNote?.trim()?`\n\nDriveDrop review note: ${d.resolutionNote.trim()}`:''}\n\nYou can view the latest booking, dispute and payout status in your DriveDrop account.`,ctaLabel:'View delivery',ctaPath:transporterPath})])}
  if(d.status==='CLOSED'&&result.previousStatus!=='CLOSED')await Promise.all([createNotificationSafely({userId:b.customer.id,type:'DISPUTE',title:'Dispute closed',body:`DriveDrop has closed the dispute for the ${vehicle}.${d.resolutionNote?.trim()?` ${d.resolutionNote.trim()}`:''}`,href:customerPath}),createNotificationSafely({userId:b.transporter.id,type:'DISPUTE',title:'Dispute closed',body:`DriveDrop has closed the dispute for the ${vehicle}.${d.resolutionNote?.trim()?` ${d.resolutionNote.trim()}`:''}`,href:transporterPath})]);
  return NextResponse.json(result.updated);
 }catch(e:any){return NextResponse.json({error:e.message||'Unable to review dispute'},{status:400})}
}
