import {NextResponse} from 'next/server';
import {prisma} from '@/lib/prisma';
import {currentUser} from '@/lib/auth';
import {disputesEnabled} from '@/lib/features';
import {sendTransactionalEmailSafely} from '@/lib/email';
import {z} from 'zod';

const Review=z.object({disputeId:z.string().min(1),status:z.enum(['UNDER_REVIEW','RESOLVED','CLOSED']),resolution:z.enum(['REFUND_CUSTOMER','PARTIAL_REFUND','RELEASE_PAYOUT','NO_ACTION','OTHER']).optional(),resolutionNote:z.string().trim().max(2000).optional(),refundAmountPence:z.number().int().positive().optional()});
const disabled=()=>NextResponse.json({error:'Disputes are not enabled in this environment'},{status:404});
const resolutionLabel=(r?:string)=>({REFUND_CUSTOMER:'Refund customer',PARTIAL_REFUND:'Partial refund',RELEASE_PAYOUT:'Release transporter payout',NO_ACTION:'No action',OTHER:'Other resolution'}[r||'']||'Resolved');

export async function GET(){if(!disputesEnabled())return disabled();const u=await currentUser();if(!u||u.role!=='ADMIN')return NextResponse.json({error:'Admin access required'},{status:403});return NextResponse.json(await prisma.dispute.findMany({include:{raisedBy:{select:{id:true,name:true,email:true,role:true}},booking:{include:{job:true,customer:{select:{name:true,email:true}},transporter:{select:{name:true,email:true}},payment:true}}},orderBy:[{status:'asc'},{createdAt:'desc'}]}))}

export async function PATCH(r:Request){
 if(!disputesEnabled())return disabled();const u=await currentUser();if(!u||u.role!=='ADMIN')return NextResponse.json({error:'Admin access required'},{status:403});const parsed=Review.safeParse(await r.json());if(!parsed.success)return NextResponse.json({error:'Invalid dispute review'},{status:400});const d=parsed.data;if(d.status==='RESOLVED'&&!d.resolution)return NextResponse.json({error:'A resolution is required when resolving a dispute'},{status:400});
 try{
  const result=await prisma.$transaction(async(tx:any)=>{
   const dispute=await tx.dispute.findUniqueOrThrow({where:{id:d.disputeId},include:{booking:{include:{payment:true,job:true,customer:{select:{name:true,email:true}},transporter:{select:{name:true,email:true}}}}}});const payment=dispute.booking.payment;let refundAmountPence=0;
   if(d.status==='UNDER_REVIEW'&&payment&&payment.payoutStatus!=='PAID'&&payment.payoutStatus!=='CANCELLED'&&payment.payoutStatus!=='HELD')await tx.bookingPayment.update({where:{id:payment.id},data:{payoutStatus:'HELD'}});
   if(d.status==='RESOLVED'&&d.resolution==='RELEASE_PAYOUT'&&payment){if(payment.status!=='PAID')throw new Error('Customer payment must be paid before payout can be released');if(dispute.booking.status!=='DELIVERED'||!dispute.booking.customerConfirmedAt)throw new Error('Delivery and customer confirmation are required before payout can be released');if(payment.payoutStatus==='PAID')throw new Error('Payout has already been released');await tx.bookingPayment.update({where:{id:payment.id},data:{payoutStatus:'READY'}})}
   if(d.status==='RESOLVED'&&d.resolution==='NO_ACTION'&&payment&&payment.payoutStatus==='HELD'){const eligible=payment.status==='PAID'&&dispute.booking.status==='DELIVERED'&&!!dispute.booking.customerConfirmedAt;await tx.bookingPayment.update({where:{id:payment.id},data:{payoutStatus:eligible?'READY':'NOT_READY'}})}
   if(d.status==='RESOLVED'&&['REFUND_CUSTOMER','PARTIAL_REFUND'].includes(d.resolution||'')){
    if(!payment)throw new Error('No payment exists for this booking');if(payment.payoutStatus==='PAID')throw new Error('Cannot refund after transporter payout has been released');if(payment.paidPence<=0)throw new Error('No captured customer payment to refund');const refundable=payment.paidPence-payment.refundedPence;if(refundable<=0)throw new Error('Customer payment has already been fully refunded');
    refundAmountPence=d.resolution==='REFUND_CUSTOMER'?refundable:(d.refundAmountPence||0);if(d.resolution==='PARTIAL_REFUND'&&refundAmountPence<=0)throw new Error('Enter a partial refund amount');if(refundAmountPence>refundable)throw new Error('Refund exceeds the remaining paid balance');if(d.resolution==='PARTIAL_REFUND'&&refundAmountPence===refundable)throw new Error('Use Refund Customer for a full remaining refund');const refunded=payment.refundedPence+refundAmountPence;const paymentStatus=refunded===payment.paidPence?'REFUNDED':'PARTIALLY_REFUNDED';
    await tx.bookingPayment.update({where:{id:payment.id},data:{refundedPence:refunded,status:paymentStatus,payoutStatus:'HELD'}});await tx.financeEvent.create({data:{paymentId:payment.id,type:'REFUND_CREATED',amountPence:refundAmountPence,actorId:u.id,note:`Dispute resolution refund — ${d.resolution==='REFUND_CUSTOMER'?'full':'partial'}`}});
   }
   const updated=await tx.dispute.update({where:{id:d.disputeId},data:{status:d.status,resolution:d.resolution,resolutionNote:d.resolutionNote,reviewerId:u.id,reviewedAt:new Date()}});return{updated,booking:dispute.booking,wasResolved:dispute.status==='RESOLVED',refundAmountPence};
  });
  if(d.status==='RESOLVED'&&!result.wasResolved){const b=result.booking;const vehicle=[b.job.vehicleYear,b.job.vehicleMake,b.job.vehicleModel].filter(Boolean).join(' ').replace(/\s+/g,' ').trim()||'vehicle';const outcome=resolutionLabel(d.resolution);const refund=result.refundAmountPence>0?`\n\nRefund recorded: £${(result.refundAmountPence/100).toFixed(2)}`:'';const note=d.resolutionNote?.trim()?`\n\nDriveDrop review note: ${d.resolutionNote.trim()}`:'';await Promise.all([sendTransactionalEmailSafely({to:b.customer.email,subject:`DriveDrop dispute resolved — ${vehicle}`,heading:'Dispute resolved',preheader:`DriveDrop has resolved the dispute for your ${vehicle} booking.`,body:`Hi ${b.customer.name?.trim()||'there'},\n\nDriveDrop has completed its review of the dispute regarding the ${vehicle}.\n\nResolution: ${outcome}${refund}${note}\n\nYou can view the latest booking and dispute status in your DriveDrop account.`,ctaLabel:'View booking',ctaPath:'/customer'}),sendTransactionalEmailSafely({to:b.transporter.email,subject:`DriveDrop dispute resolved — ${vehicle}`,heading:'Dispute resolved',preheader:`DriveDrop has resolved the dispute for the ${vehicle} booking.`,body:`Hi ${b.transporter.name?.trim()||'there'},\n\nDriveDrop has completed its review of the dispute regarding the ${vehicle}.\n\nResolution: ${outcome}${refund}${note}\n\nYou can view the latest booking, dispute and payout status in your DriveDrop account.`,ctaLabel:'View delivery',ctaPath:'/transporter'})])}
  return NextResponse.json(result.updated);
 }catch(e:any){return NextResponse.json({error:e.message||'Unable to review dispute'},{status:400})}
}
