'use client';
import {useState} from 'react';
import Link from 'next/link';
import s from '../../payments/payments.module.css';
import v from './desktop.module.css';
import {proceedsPeriod,periodQuery,periodDescription,inProceedsPeriod,londonDate,type PeriodParams} from '@/lib/payment-period';
import {filterProceeds,proceedsStatus,proceedsReference,proceedsNet} from '@/lib/proceeds-filters';
import {paymentMoney as money,paymentDate as date,paymentLabel as label} from '@/lib/customer-payments';
function Icon({name}:{name:string}){const paths:Record<string,string>={download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',calendar:'M4 4h16v18H4ZM8 2v5m8-5v5M4 10h16',car:'M3 15v-4l3-1 3-5h7l4 5 3 1v4h-3m-4 0H8M8 10h11M8 15a2 2 0 1 1-4 0 2 2 0 0 1 4 0m13 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0',van:'M2 17V4h13l7 7v6h-3M6 17h9M15 4v7h7M7 17a2 2 0 1 1-4 0 2 2 0 0 1 4 0m12 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0',list:'M8 5h14M8 12h14M8 19h14M2 5h1M2 12h1M2 19h1',receipt:'M5 2h14v20H5ZM8 7h8M8 11h8M8 15h5',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',booked:'M21 5c0 2-4 3-9 3S3 7 3 5s4-3 9-3 9 1 9 3ZM3 5v14c0 2 4 3 9 3s9-1 9-3V5M3 10c0 2 4 3 9 3s9-1 9-3M3 15c0 2 4 3 9 3s9-1 9-3',progress:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M12 6v6l4 3',ready:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0m-15-1 3 3 7-7',held:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0M9 7v10m6-10v10',fine:'M12 2 1 22h22ZM12 8v6m0 4h.01'};
return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.receipt}/></svg>}
function Badge({text,green=false}:{text:string;green?:boolean}){return <span className={s.status+' '+(green?s.paid:s.refunded)}>{text}</span>}
export default function ProceedsDesktop({bookings,initial}:{bookings:any[];initial:PeriodParams&{filter?:string;adjustment?:string}}){
 const [period,setPeriod]=useState(()=>{try{return proceedsPeriod(initial)}catch{return proceedsPeriod({})}});
 const [q,setQ]=useState(''),[month,setMonth]=useState(''),[status,setStatus]=useState((initial.filter||'BOOKED').toUpperCase()),[adjustment,setAdjustment]=useState((initial.adjustment||'ALL').toUpperCase()),[selectedId,setSelectedId]=useState(''),[error,setError]=useState('');
 const all=bookings.filter(r=>r.payment),years=Array.from(new Set([period.currentYear,...all.map(r=>Number(londonDate(r.createdAt).slice(0,4)))])).sort((a,b)=>b-a);
 const periodRows=all.filter(r=>inProceedsPeriod(r,period));
 const base=filterProceeds(periodRows,{q,month});
 const rows=filterProceeds(base,{status,adjustment});
 const selected=rows.find(r=>r.id===selectedId)||rows[0];
 const sum=(key:string)=>filterProceeds(base,{status:key}).reduce((n,r)=>n+proceedsNet(r)+(r.payment.cancellationDeductionPence||0),0);
 const fines=base.reduce((n,r)=>n+(r.payment.cancellationDeductionPence||0),0),refunds=base.reduce((n,r)=>n+(r.payment.refundedPence||0),0);
 const months=Array.from(new Set(periodRows.flatMap(r=>r.job.collectionDate?[londonDate(r.job.collectionDate).slice(0,7)]:[]))).sort().reverse();
 const download=(format:string,id?:string)=>'/api/transporter/proceeds/export?'+new URLSearchParams({...Object.fromEntries(periodQuery(period)),format,q,month,status,adjustment,...(id?{bookingId:id}:{})}).toString();
 const tiles=[['BOOKED','Booked proceeds','booked'],['IN_PROGRESS','In progress','progress'],['READY','Ready for release','ready'],['HELD','Held','held'],['PAID','Paid','receipt'],['FINES','Fines / Refunds','fine']];
 return <main className={s.page+' '+v.desktop}>
 <header className={s.heading}><div><h1>Booked proceeds</h1><p>See the proceeds attached to every active and completed delivery, including payout progress and any fine deductions.</p></div></header>
 <section className={s.periodToolbar} aria-label="Yearly statements">
 <label className={s.yearSelect}>Year<select value={period.year??'custom'} onChange={e=>{if(e.target.value!=='custom'){setPeriod(proceedsPeriod({year:e.target.value}));setMonth('')}}}>{period.year===null&&<option value="custom">Custom date range</option>}{years.map(y=><option key={y} value={y}>{y}{y===period.currentYear?' (current)':''}</option>)}</select></label><span className={s.periodDates}>{periodDescription(period)}</span>
 <details className={s.dateRange}><summary><Icon name="calendar"/>Custom date range <span>⌄</span></summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{setPeriod(proceedsPeriod({start:String(f.get('start')),end:String(f.get('end'))}));setMonth('');setError('');e.currentTarget.closest('details')?.removeAttribute('open')}catch(err){setError((err as Error).message)}}}><label>Start date<input type="date" name="start" defaultValue={period.start} key={period.start} required/></label><label>End date<input type="date" name="end" defaultValue={period.end} key={period.end} required/></label>{error&&<p role="alert">{error}</p>}<button>Apply date range</button></form></details>
 <div className={s.downloadActions}><a href={download('pdf')}><Icon name="download"/>Download PDF</a><a href={download('csv')}><Icon name="download"/>Export CSV</a></div></section>
 <nav className={v.tiles} aria-label="Filter proceeds">{tiles.map(([key,title,icon])=><button key={key} className={status===key?v.active:undefined} onClick={()=>{setStatus(key);setAdjustment('ALL')}} aria-pressed={status===key}><Icon name={icon}/><div><span>{title}</span>{key==='FINES'?<div className={v.adjustments}><span>Fines <b>−{money(fines)}</b></span><span>Refunded <b>{money(refunds)}</b></span></div>:<strong>{money(sum(key))}</strong>}</div></button>)}</nav>
 <p className={v.note}>Proceeds totals shown before fines.</p>
 <div className={s.columns}><section className={s.history}><div className={s.sectionHeading}><h2><Icon name="list"/>Proceeds history</h2><span aria-live="polite">{rows.length} bookings</span></div>
 <div className={s.filters}><input aria-label="Search booking or vehicle" placeholder="Search booking or vehicle" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Collection month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">All dates</option>{months.map(m=><option key={m} value={m}>{new Date(m+'-01T12:00:00Z').toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</option>)}</select><select aria-label="Payout status" value={status} onChange={e=>setStatus(e.target.value)}><option value="BOOKED">All statuses</option><option value="IN_PROGRESS">In progress</option><option value="READY">Ready for release</option><option value="HELD">Held</option><option value="PAID">Paid</option><option value="CANCELLED">Payout cancelled</option><option value="FINES">Fines / Refunds</option></select></div>
 {status==='FINES'&&<label className={v.adjustmentFilter}>Show <select value={adjustment} onChange={e=>setAdjustment(e.target.value)}><option value="ALL">All fines and refunds</option><option value="FINES">Fines only</option><option value="REFUNDS">Refunds only</option></select></label>}
 <div className={s.tableScroll}><table><thead><tr><th>Booking / vehicle</th><th>Collection date</th><th>Net proceeds</th><th>Payout status</th><th>Statement</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={selected?.id===r.id?s.selected:''} onClick={()=>setSelectedId(r.id)}><td><button className={s.selectRow} aria-pressed={selected?.id===r.id} onClick={()=>setSelectedId(r.id)}><Icon name={/van|transit|sprinter|motorhome/i.test(r.vehicleType||r.job.vehicleModel)?'van':'car'}/><strong>{proceedsReference(r.id)}</strong><span>{r.job.vehicleMake} {r.job.vehicleModel}</span></button></td><td>{date(r.job.collectionDate)}</td><td>{money(proceedsNet(r))}</td><td><Badge text={proceedsStatus(r)} green={['READY','PAID'].includes(r.payment.payoutStatus)}/></td><td>{r.status==='DELIVERED'?<a className={s.iconButton} aria-label={'Download statement for '+proceedsReference(r.id)} href={download('pdf',r.id)}><Icon name="download"/></a>:'—'}</td></tr>)}</tbody></table></div>
 {!rows.length&&<div className={s.empty}><h3>No matching proceeds</h3><p>Try another search, date or status.</p></div>}
 </section><aside className={s.breakdown} aria-label="Selected proceeds breakdown"><h2><Icon name="receipt"/>Proceeds breakdown</h2>{selected?<><small className={s.bookingLabel}>Booking</small><strong>{proceedsReference(selected.id)}</strong><p className={s.vehicle}>{selected.job.vehicleMake} {selected.job.vehicleModel}</p><p className={v.customer}>{selected.customer.name}{selected.job.registration?' · '+selected.job.registration:''}</p>
 <div className={s.journey}><div><Icon name="pin"/><div><small>Collection</small><span>{selected.job.collection}</span></div></div><div><Icon name="pin"/><div><small>Delivery</small><span>{selected.job.delivery}</span></div></div></div>
 <dl className={s.amounts}><div><dt>Proceeds before fine</dt><dd>{money(proceedsNet(selected)+(selected.payment.cancellationDeductionPence||0))}</dd></div><div><dt>Fine deducted</dt><dd className={v.fine}>−{money(selected.payment.cancellationDeductionPence||0)}</dd></div><div><dt>Net proceeds</dt><dd>{money(proceedsNet(selected))}</dd></div><div><dt>Customer refund</dt><dd>{money(selected.payment.refundedPence||0)}</dd></div></dl>
 <dl className={s.meta}><div><dt>Collection date</dt><dd>{date(selected.job.collectionDate)}</dd></div><div><dt>Delivery status</dt><dd><Badge text={label(selected.status)} green={selected.status==='DELIVERED'}/></dd></div><div><dt>Paid on</dt><dd>{date(selected.payment.events[0]?.createdAt||null)}</dd></div><div><dt>Payout status</dt><dd><Badge text={proceedsStatus(selected)} green={['READY','PAID'].includes(selected.payment.payoutStatus)}/></dd></div></dl>
 {selected.status==='DELIVERED'&&<a className={s.button+' '+s.orange} href={download('pdf',selected.id)}><Icon name="download"/>Download statement (PDF)</a>}<Link className={s.button+' '+s.viewBooking} href={(selected.status==='DELIVERED'?'/transporter/delivered':selected.status==='CANCELLED'?'/transporter?view=cancelled':'/transporter?view=deliveries')+'#booking-'+encodeURIComponent(selected.id)}>View booking</Link>
 </>:<p>Select a booking to view its breakdown.</p>}</aside></div><p className={s.archiveNote}>A new year starts automatically. Previous years stay available to view and download.</p>
 </main>;
}
