'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';

type Notification={id:string;type:string;title:string;body:string;href:string|null;readAt:string|null;createdAt:string};
const icon=(type:string)=>type==='QUOTE'?'£':type==='BOOKING'?'✓':type==='PAYMENT'?'£':type==='DELIVERY'?'🚗':type==='MESSAGE'?'💬':type==='DISPUTE'?'!':type==='REVIEW'?'★':type==='VERIFICATION'?'🛡️':'🔔';
const destination=(n:Notification)=>n.type==='QUOTE'?'/customer?view=quotes#quote-requests':n.type==='BOOKING'?'/transporter?view=deliveries':n.type==='PAYMENT'?'/transporter?view=deliveries':n.type==='DELIVERY'?'/customer?view=bookings':n.type==='MESSAGE'?'/messages':n.href;
const tone=(type:string)=>type==='DISPUTE'?'danger':type==='PAYMENT'||type==='QUOTE'?'finance':type==='VERIFICATION'?'compliance':type==='DELIVERY'||type==='BOOKING'?'delivery':'standard';

export default function NotificationsPage(){
 const[items,setItems]=useState<Notification[]>([]),[loading,setLoading]=useState(true),[expanded,setExpanded]=useState<string|null>(null);
 async function load(){const r=await fetch('/api/notifications',{cache:'no-store'});if(r.ok){const d=await r.json();setItems(d.notifications||[])}setLoading(false)}
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 async function mark(id:string){await fetch('/api/notifications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id})});setItems(x=>x.map(n=>n.id===id?{...n,readAt:new Date().toISOString()}:n));window.dispatchEvent(new Event('drivedrop:notifications-read'))}
 async function markAll(){await fetch('/api/notifications',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({all:true})});setItems(x=>x.map(n=>({...n,readAt:n.readAt||new Date().toISOString()})));window.dispatchEvent(new Event('drivedrop:notifications-read'))}
 const unread=items.filter(n=>!n.readAt).length;
 const grouped=useMemo(()=>{const now=new Date(),todayKey=now.toDateString();const today:Notification[]=[],earlier:Notification[]=[];items.forEach(n=>(new Date(n.createdAt).toDateString()===todayKey?today:earlier).push(n));return{today,earlier}},[items]);
 const renderGroup=(title:string,rows:Notification[])=><>{rows.length>0&&<section className="notificationGroup"><div className="notificationGroupHeading"><h2>{title}</h2><span>{rows.length}</span></div><div className="notificationList">{rows.map(n=>{const href=destination(n),open=expanded===n.id,isUnread=!n.readAt;return <article key={n.id} className={`dashboardCard notificationCard ${isUnread?'isUnread':''} ${open?'isExpanded':''} ${tone(n.type)}`}><button type="button" className="notificationSummary" onClick={()=>setExpanded(open?null:n.id)} aria-expanded={open}><span className="notificationIcon">{icon(n.type)}</span><span className="notificationSummaryCopy"><span className="notificationMetaLine"><b>{n.title}</b>{isUnread&&<span className="notificationNewBadge">New</span>}</span><small>{new Date(n.createdAt).toLocaleString('en-GB')}</small></span><span className="notificationType">{n.type.replaceAll('_',' ').toLowerCase()}</span><span className="notificationChevron">{open?'−':'+'}</span></button>{open&&<div className="notificationExpanded"><p>{n.body}</p><div className="notificationActions">{href&&<Link className="btn light" href={href} onClick={()=>mark(n.id)}>View related activity</Link>}{isUnread&&<button className="textAction" onClick={()=>mark(n.id)}>Mark as read</button>}</div></div>}</article>})}</div></section>}</>;
 return <main className="shell dashboardShell notificationsPage"><Link className="backLink" href="/">← Back</Link><header className="dashboardHero notificationsHero"><div><span className="dashboardEyebrow">Account activity</span><h1>Notifications</h1><p>Important DriveDrop updates about quotes, bookings, payments, deliveries, messages and account actions.</p></div><div className="adminHeroBadge notificationHeroBadge"><span>Unread</span><strong>{unread}</strong><small>Notification{unread===1?'':'s'}</small></div></header><div className="notificationToolbar"><div><span className="dashboardEyebrow dark">Activity centre</span><h2>Recent activity</h2></div>{unread>0&&<button className="btn light" onClick={markAll}>Mark all as read</button>}</div>{loading?<div className="dashboardCard">Loading notifications…</div>:items.length===0?<div className="dashboardCard emptyState"><div>🔔</div><h3>No notifications yet</h3><p>Important marketplace activity will appear here.</p></div>:<>{renderGroup('Today',grouped.today)}{renderGroup('Earlier',grouped.earlier)}</>}</main>;
}
