'use client';

import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useEffect,useState} from 'react';

export default function Register(){
  const router=useRouter();const [transporter,setTransporter]=useState(false);const [err,setErr]=useState('');const [showPassword,setShowPassword]=useState(false);
  useEffect(()=>{setTransporter(new URLSearchParams(window.location.search).get('account')==='transporter');},[]);
  async function submit(e:any){e.preventDefault();setErr('');const f=new FormData(e.currentTarget);const res=await fetch('/api/auth/register',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});const d=await res.json();if(!res.ok)return setErr(d.error);router.push(d.role==='CUSTOMER'?'/customer':'/transporter');router.refresh();}
  return <main className="authPage"><section className="authVisual registerVisual"><div className="authOverlay"/><div className="authVisualContent"><Link className="authBrand" href="/">Drive<span>Drop</span></Link><span className="dashboardEyebrow">Join the vehicle transport marketplace</span><h1>{transporter?'Grow your transport work with DriveDrop.':'Get your vehicle moving.'}</h1><p>{transporter?'Create your transporter account to quote on jobs, manage deliveries, upload evidence and build a verified profile.':'Create a customer account to request transport, compare quotes and manage your delivery from one dashboard.'}</p><div className="authTrust"><span>✓ Fast account setup</span><span>✓ Secure marketplace</span><span>✓ Mobile-friendly dashboard</span></div></div></section><section className="authPanel"><div className="authCard"><Link className="backLink" href="/">← Back to DriveDrop</Link><div className="authHeading"><span className="dashboardEyebrow dark">Create account</span><h2>{transporter?'Join as a transporter':'Join DriveDrop'}</h2><p>{transporter?'Set up your transporter account. Verification and insurance details can be completed from your dashboard.':'Set up your customer account and start requesting vehicle transport quotes.'}</p></div><form onSubmit={submit}><div className="field"><label>NAME / BUSINESS NAME</label><input name="name" placeholder={transporter?'Your name or business name':'Your name'} required/></div><div className="field"><label>EMAIL ADDRESS</label><input type="email" name="email" autoComplete="email" placeholder="you@example.com" required/></div><div className="field"><label>PASSWORD</label><div className="password-wrap"><input type={showPassword?'text':'password'} name="password" minLength={8} autoComplete="new-password" placeholder="Minimum 8 characters" required/><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?'Hide':'Show'}</button></div></div><div className="field"><label>ACCOUNT TYPE</label><select name="role" value={transporter?'TRANSPORTER':'CUSTOMER'} onChange={e=>setTransporter(e.target.value==='TRANSPORTER')}><option value="CUSTOMER">Customer</option><option value="TRANSPORTER">Transporter</option></select></div>{err&&<div className="formNotice errorNotice">{err}</div>}<button className="btn orange authSubmit">Create my account</button></form><div className="authDivider"><span>Already registered?</span></div><Link className="authSecondary" href={transporter?'/login?account=transporter':'/login'}>Sign in →</Link><p className="authFootnote">By creating an account you can access DriveDrop’s secure marketplace features.</p></div></section></main>;
}
